### ISSUE TITLE
Question: Where does NanoVNA-saver store the user calibration standard values?

### ISSUE THREAD

**Issue by Harry-ei6ku** [NanoVNA-Saver/nanovna-saver#109]
I'd like to save my user calibration standard values to a dropbox and use them across different PCs, but I can't find where NanoVNA-saver saves these user values? can someone point me to the location pls.

73

Harry

**Comment by mihtjel** [comment]
Hi,
on startup, the application writes in the console window where
NanoVNASaver.ini is placed - that's the file that also contains the
calibration standard sets.

-- 
Rune / 5Q5R

**Comment by Harry-ei6ku** [comment]
Understood, thank you.

Harry
