### ISSUE TITLE
Smith Chart Labels

### ISSUE THREAD

**Issue by acug01** [NanoVNA-Saver/nanovna-saver#127]
Useful addition would be to put major division labels on the Smith Chart, e.g., normalized integers on right hand real axis, decimals on left; similar on outer imaginary circle.  Perhaps also, additional divisions, such as on the legacy printed charts?  Thanks!

**Comment by mihtjel** [comment]
More could certainly be done with the Smith chart!

**Comment by satfan52** [comment]
It would be nice as well to have some admittance circles drawn on the display not only the impedance ones. It is as convenient to visualize the admittance circle for Y=1 then the circle Z=1, both should be ideally displayed. Maybe displaying the admittance circles could be another option to set in the parameters
