### ISSUE TITLE
NanoVNASaver 0.0.9 - Add auto scale for the VSWR

### ISSUE THREAD

**Issue by RolandWa** [NanoVNA-Saver/nanovna-saver#13]
Hi mihtjel,

Please add the autoscale for the VSWR

Best regards
Roland

**Comment by mihtjel** [comment]
VSWR is autoscaled to a max of 25 currently, as VSWR measurements above that are rarely very useful. I'm looking into customized scaling for all the charts, and will surely add an option to change the max for VSWR when that comes in.

**Comment by zarath** [comment]
Outdated Issue
