### ISSUE TITLE
Span < 2Hz not allowed

### ISSUE THREAD

**Issue by hiperiondev** [NanoVNA-Saver/nanovna-saver#138]
NanoVNA fw 0.5.4 allow Span of 1Hz but NanoVNAsaver unable to parse frequency

**Comment by mihtjel** [comment]
I'll need some more information on this - what values are you entering that fail to parse?

**Comment by hiperiondev** [comment]
In sweep control if set Span = 1Hz and push Sweep returns: Unable to parse frequency inputs - check start and stop fields.

But in device you can set 1Hz of Span

**Comment by zarath** [comment]
Should work in v0.3.5
