### ISSUE TITLE
NanoVNASaver 0.0.9 - Add the zoom function on the figure

### ISSUE THREAD

**Issue by RolandWa** [NanoVNA-Saver/nanovna-saver#15]
Hi mihtjel,

Please add the zoom function using the mouse wheel, and by use the rectangle draw by mouse.

Best Regards
Roland

**Comment by df6dbf** [comment]
Its maybe easier to transfer the frequency value from an Marker-Field to the Start/Stop-Fields. So you can mark your area of interest and with the next sweep you got the values. :)

**Comment by zarath** [comment]
Zooming was in v0.2.2
