### ISSUE TITLE
Start Stop Frequency boxes layout issue

### ISSUE THREAD

**Issue by ast** [NanoVNA-Saver/nanovna-saver#154]
There seems to be a small issue with layout of the start/stop/center/stap textboxes, they are too small on my machine Ubuntu 18.04.4 LTS 1920x1080.

Just pulled latest version from github, 0.2.2 is displayed.

![Screenshot from 2020-02-07 12-16-24](https://user-images.githubusercontent.com/130054/74025263-d75e4d80-49a3-11ea-8e5b-7abbbebb0f98.png)

**Comment by zarath** [comment]
more ideas in #251
