### ISSUE TITLE
I have a problem with saving the calibration

### ISSUE THREAD

**Issue by rmalsbury50** [NanoVNA-Saver/nanovna-saver#157]
https://youtu.be/MF5ZYTSwCgI

**Comment by petem001** [comment]
private video we cant see it


________________________________________
De : rmalsbury50 <notifications@github.com>
Envoyé : 11 février 2020 14:41
À : mihtjel/nanovna-saver
Cc : Subscribed
Objet : [mihtjel/nanovna-saver] I have a problem with saving the calibration (#157)

https://youtu.be/MF5ZYTSwCgI

**Comment by zarath** [comment]
Please reopen and enable video access if still a problem with > v0.3.0
