### ISSUE TITLE
Display Convulsing On First Use

### ISSUE THREAD

**Issue by cmoher3** [NanoVNA-Saver/nanovna-saver#167]
I just downloaded the latest version and upon clicking the .exe, it loaded

 but it is violently convulsing or twitching. Not sure what that is all about or the fix ??

**Comment by mihtjel** [comment]
Hi,
that doesn't sound like anything I can recognise. It's certainly not an intended feature of the software.

What OS? What size screen do you have? Do you have any special settings, such as custom fonts or font size configured?
