### ISSUE TITLE
Scan command at edy555 release 0.7.1

### ISSUE THREAD

**Issue by DiSlord** [NanoVNA-Saver/nanovna-saver#170]
Scan command modified

Now syntax is:
scan {start(Hz)} {stop(Hz)} [points] [outmask]
[outmask] - optional, allow output measured data, its a mask (allow dec, hex, bin, oct)
0b001 - output frequency
0b010 - output CH0 data
0b100 - output CH1 data
Example:
'scan 1000000 5000000 101 0b111' - output data in format: freq ch0[0] ch0[1] ch1[0] ch1[1]
'scan 1000000 5000000 101 0b101' - output data in format: freq ch1[0] ch1[1]
'scan 1000000 5000000 101 0x7' - output data as 0b111

In future i possibly add interpolation calc on fly, then it possible set any points count (now it limit 101)

**Comment by zarath** [comment]
Implemented in current Development for NanoVNA orginial firmware ...don't have firmware version number information of alternative firmwares or hardware...
