### ISSUE TITLE
how to make nanovnasaver.exe so small

### ISSUE THREAD

**Issue by dorappp** [NanoVNA-Saver/nanovna-saver#174]
how to make the nanovansaver.exe so samll,I try to use the virtualenv，but it's also too big

**Comment by zarath** [comment]
What is small and what is too big? And why this is a Bug?

**Comment by dorappp** [comment]
NO,It's not bug,I just want to know how you can install it so small.
when I install some python program include numpy to the .exe, it's always too big.&nbsp;
Would you like to teache me?



---Original---

**Comment by zarath** [comment]
Is the actual binary (v0.3.2) still smaller then yours?

It's just created with pyinstaller.

**Comment by dorappp** [comment]
....OK&nbsp; Thank you.&nbsp; I'll try again



---Original---

**Comment by dorappp** [comment]
sorry to bother you.
I'm&nbsp; confused about the communication protocol between NanoVNASaver and NanoVNA-H.
Waht's the&nbsp;Communication data format of them.Where to get the&nbsp; relevant information.
Thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NanoVNA-Saver/nanovna-saver"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年6月29日(星期一) 晚上8:04
收件人:&nbsp;"NanoVNA-Saver/nanovna-saver"<nanovna-saver@noreply.github.com&gt;;
抄送:&nbsp;"_____.暮夜"<2013352710@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NanoVNA-Saver/nanovna-saver] how to make nanovnasaver.exe so small (#174)





 
Is the actual binary (v0.3.2) still smaller then yours?
 
It's just created with pyinstaller.
