### ISSUE TITLE
Data outside frequency span

### ISSUE THREAD

**Issue by Toontje** [NanoVNA-Saver/nanovna-saver#175]
**Describe the bug**
VSWR screen doesn't update when scan range is outside of currently displayed range

**To Reproduce**
1. Select VSWR trace
2. Run a trace from 100-200MHz
3. Change Sweep Control Start to 300 and finish to 400
4. Run sweep again
5. Screen stays on 100-200MHz span and shows "Data outside frequency range". No way (at least known to me) to change span.

**Expected behavior**
Screen updates to show 300-400MHz span with latest trace.

**Screenshots**
<img width="1323" alt="Screenshot 2020-04-28 at 20 42 05" src="https://user-images.githubusercontent.com/4884243/80525076-f5c75a00-8990-11ea-9d15-4b832e9be843.png">

**Desktop (please complete the following information):**
 - OS: OSX 10.15.4
 - Python version: 3.7.7
 - NanoVNA-Saver version: 0.2.2

**Additional context**

**Comment by zarath** [comment]
Not reproducable in current version (v0.3.1)
