### ISSUE TITLE
Calculate the Common Mode Rejection Ratio (CMRR) of a Balun

### ISSUE THREAD

**Issue by satfan52** [NanoVNA-Saver/nanovna-saver#189]
references:
http://www.arrl.org/files/file/QEX_Next_Issue/Nov-Dec_2010/Skelton_QEX_Nov-Dec.pdf
and
https://dokumen.tips/download/link/a-wideband-balun-for-hf-vhf-and-uhf-applications

When measuring the performance of a two port balun where one port is single ended (asymetrical)  and the second port is balanced (symetrical), typically to connect a coax to a symetrical antenna or to the input of a push-pull amplifier etc.. , it is important to assess the Common Mode Rejection Ratio (and not only the impedance transforming ratio, the vswr  or the insertion loss). For instance, in the case of an antenna, the CMRR determines to which extend the balun is sucesful or not to prevent that the coaxial cable (connected on the single-ended side) radiates energy. 

This concept  is especially important for very wide-band balun aiming at covering HF+6M, or even HF+VHF+UHF up to the 70cm band (see second article/downloadable paper) to identify what is the frequency limit of the balun (usually when the CMRR degrades below 25 dB).  

Measuring the CMRR of a balun requires to build a dedicated 3 port test fixture (1 input and 2 outputs, see first article for the description of the fixture) and to make two successive S parameter transmission measurements (between the single input and the two outputs of the fixture).  

**CMRR dB =20*log (S21+S31)/(S21- S31) 
(where port 1 is the input and port 2 and 3 are the two outputs of the test fixture)** 

It would be great if Nanovna-saver could display the CMRR as one of the many possible display parameters.  The idea is that nanovna-saver would simply use the two last values of S21 measured  to calculate the CMRR based on the formula above

**Comment by AD5U** [comment]
satfan52 - THANKS!  Thanks for including links to references in your post.  I read the article on the wideband balun with great interest as my friend and I have been researching making our own transformer+chokes for uses at HF, VHF and UHF bands.  I had expected that we would need to make multiple baluns for the various bands but that may change now.

Additionally we have been researching effective ways to test baluns and chokeswith our nanoVNA units (we love them!) and were thinking of fixture(s) that might be needed and we have more ideas now.  If we come up with things that actually work, we'll contribute.

The linked info also gave me more ideas for testing with some of the fancy analyzer(s) I use for work.  Some are programmable and/or remotely operable with data then made available to the computer for additional processing.  I might be able to work out the process and number crunching and then see what I can do with my nanoVNA units.  If I can, I will try to contribute something to the software project.

Thanks for the inspirations you have provided me!
Scott
AD5U

**Comment by satfan52** [comment]
Hi Scott,

You are welcome.

 I have (not yet) tried to use the measurement techniques described in these two articles. If you do it before me, it would make sense to report here if the formula cited in the article (to measure the CMMR gives) good practical results or not.  

CMRR dB =20*log (S21+S31)/(S21- S31)

If not, there is no need to waste coding time on this. 

Another way to implement this with nanovna-saver that might be simpler to understand  for the end-user but a bit more challenging to implement for the coder, is  simply to provide the possibility in the FILE menu to "import an S2P file as  S31" . Then up to the user to choose display CMRR in the list of possible "display charts" and/or in the list of markers data.
