### ISSUE TITLE
Add marker for TDR

### ISSUE THREAD

**Issue by gaionim** [NanoVNA-Saver/nanovna-saver#19]
Hi,
a marker for TDR could be useful to identify distance of junction ( or other anomaly).

73

**Comment by mihtjel** [comment]
It sounds like an interesting idea! It probably needs the TDR graph to be scalable as well, if it's really to be of any value. I'll consider it :-)

**Comment by gaionim** [comment]
I noticed that the full scale value is a function of the stimulus. Perhaps we could investigate further and set stimulus based on the desired length (10m, 100m etc)

**Comment by gaionim** [comment]
stimulus full-scale
1-30m 1.3km
1-300m 133m
1-900m 44m
1-1500m  26m

**Comment by frohro** [comment]
Is there a way to use the TDR to measure a 1000 foot cable that has a break somewhere in it, to determine where the break is?

**Comment by zarath** [comment]
Marker is implemented.

Perhaps a documentation chapter does and don'ts for TDR are nice in future
