### ISSUE TITLE
Binary Release 3.0  and Dev release 3.2 - Ubuntu 18.04 LTS -  s2p files export - erronous S21 data 

### ISSUE THREAD

**Issue by satfan52** [NanoVNA-Saver/nanovna-saver#202]
Hello,

This was tested with a nanovna V1 (classical) 

Two points

1) after exporting S2p files in SimSmith, I noticed that S11 data is OK but S21 is not, there is obviously something very wrong with the export of S21 s2p data
2)  I noticed that that the data exported for S21 is the same independently of the attenuation setting chosen for CH1. I am no sure if this is by design or not but this seems to me inadequate. After 1 is fixed,  it would be great that s2p data exported takes into account the effect of the CH1 attenuation settings

See pictures below, the first one shows that the CH1 attenuation settings works well (40dB attenuation), the second one shows that the S2p data exported is not corresponding to  any of the two  measurement (with and without CH1 attenuation settings)  

![Screenshot from 2020-06-29 23-07-09](https://user-images.githubusercontent.com/14941529/86058074-9654fb80-ba60-11ea-9281-a3b7b714ed05.png)

![Screenshot from 2020-06-29 23-18-48](https://user-images.githubusercontent.com/14941529/86058103-a1a82700-ba60-11ea-9978-98283bef0dd8.png)

**Comment by zarath** [comment]
Yes there was a bug in applying data not to s21 in calibration.
Should be fixed in current development branch.
But no fresh binaries yet

**Comment by zarath** [comment]
See v0.3.3
