### ISSUE TITLE
App size is too large in Win10

### ISSUE THREAD

**Issue by imreac** [NanoVNA-Saver/nanovna-saver#210]
When opening the latest version of NanoVNA Saver 0.3.2 in Win10, the application is too large to fit in one window view.  Whether full screen or not, the app will not fit.  Tried reducing text size, which makes a small difference, but always need to scroll around program window to see everything.  
**To Reproduce**
1. Click on desktop Icon to open NanoVNA Saver 0.3.2
2. App opens, but does not fit in window
4. See Screenshots
**Expected behavior**
Expected app to fit in window.

**Screenshots**
![image](https://user-images.githubusercontent.com/67669528/86196651-901a5a00-bb08-11ea-800e-ecc762eedb83.png)
<img width="459" alt="NanoVNA  Start" src="https://user-images.githubusercontent.com/67669528/86197050-70376600-bb09-11ea-911e-831a8725d161.PNG">
<img width="590" alt="Win 10 Version" src="https://user-images.githubusercontent.com/67669528/86197257-de7c2880-bb09-11ea-97c5-2c3cbb277326.PNG">

**Desktop (please complete the following information):**
 - OS: Win 10   (see screenshot)
 - Python version: [if applicable]
 - NanoVNA-Saver version: [e.g. 0.3.2]

**Additional context**
Deleted .ini file here: C:\Users\Admin\AppData\Roaming\NanoVNASaver   Still no difference.
Desktop Resoloution:
<img width="960" alt="Desktop Resoloution" src="https://user-images.githubusercontent.com/67669528/86197585-898ce200-bb0a-11ea-9c3e-72c39a40c68f.PNG">

On very first startup, had some message in command window to the effect that " could not get desktop resolution..."

**Comment by imreac** [comment]
Fixed issue by resetting Windows Scaling from 150% to 100%.  This unfortunately shrinks Tabs and everything else (i.e. file manager folders)
See attached screen captures:
<img width="190" alt="Windows 10 Scaling Fix" src="https://user-images.githubusercontent.com/67669528/86316370-7862d480-bbe1-11ea-8c95-5505c4de07bb.PNG">
![NanoVNA  @ 100% Windows 10 Scaling](https://user-images.githubusercontent.com/67669528/86316530-d5f72100-bbe1-11ea-9052-94faa787ba83.PNG)

**Comment by RandMental** [comment]
When there are only 4  graphs, the desktop scale correctly on the screen (1680x1050 display)
When two more are enabled e.g. all 6, the screen-width becomes too long.
The aspect ratio might need to change

![Desktop 2](https://user-images.githubusercontent.com/6272455/86364989-37b69a00-bc79-11ea-95a0-f6f646673bc3.png)

**Comment by imreac** [comment]
I had not tried this, but it needs attention.  Even if the additional 2 graphs (#5, 6) are closed, the original ones on the right  (#3, 4) are stretched.
![Nano VNA after Add - Remove Graphs 5 6](https://user-images.githubusercontent.com/67669528/86381743-6402f400-bc42-11ea-91e3-74e57887522d.PNG)
