### ISSUE TITLE
Error elementary OS 

### ISSUE THREAD

**Issue by Opensoftwarecr** [NanoVNA-Saver/nanovna-saver#219]
After executing all the instructions indicated in the installation and try run:

![image](https://user-images.githubusercontent.com/67758587/86398676-39756300-bc63-11ea-82f8-8fbd4a1cedde.png)

OS: Elementary OS 5.1.6 Hera

**Comment by f5mog** [comment]
I'm using Linux Mint 19 Cinnamon. I have exactly the same message .

**Comment by zarath** [comment]
Fixed in current Development tree
