### ISSUE TITLE
App crashes if you click Connect button with no device

### ISSUE THREAD

**Issue by MZachmann** [NanoVNA-Saver/nanovna-saver#220]
**Describe the bug**
If you run nanovna-saver and click the Connect button the app crashes.

**Expected behavior**
The app should indicate no device was found or at least do nothing

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version: [if applicable] 3.8.0
 - NanoVNA-Saver version: latest dev branch

**Comment by zarath** [comment]
Fixed by #221
