### ISSUE TITLE
% bar not running correctly when running continuous sweep

### ISSUE THREAD

**Issue by PA3CCE** [NanoVNA-Saver/nanovna-saver#222]
I'm using version 3.3 of NanoVNA-Saver.
When I perform a continuous sweep the % bar (progress bar) in the main window stops running after the first completed sweep.
I expect it should reset and start again after each completed sweep, so that you can see it's really sweeping continuously.
Minor issue.
Jos

**Comment by zarath** [comment]
Fix in https://github.com/NanoVNA-Saver/nanovna-saver/commit/71ba759adaa81af1b9643f8bf797204944bae0ba
