### ISSUE TITLE
201 datapoints setting is not possible.

### ISSUE THREAD

**Issue by PA3CCE** [NanoVNA-Saver/nanovna-saver#224]
I'm runnig NanoVNA-Saver on Windows 10 using NanoVNA-H4 with latest firmware by DiSlord.

1. Go to Main Window
2. Click on "Manage" button
3 Goto "Settings/Datapoints" in the "Device settings" window
4. See error :  201 points setting is not selectable.

**Expected behavior**
Setting 201 points should be selectable in a pulldown menu.

**Comment by zarath** [comment]
Is H4 otherwise working with v0.3.4 and latestet DiSlord firmware?

I've seen where the problem is burried.. fix will follow soon

**Comment by RandMental** [comment]
It seems to be working now. 


Only spesific item on H and H4 is the Manage - > Settings that don't offer 201 data points. I could not find last night where the 201, 101 list gets lost.

**Comment by PA3CCE** [comment]
As far as I know yes, I'm still trying out.
Jos
