### ISSUE TITLE
Erratic display behaviour with "Hide Data" in Markers and maximized

### ISSUE THREAD

**Issue by igor-m** [NanoVNA-Saver/nanovna-saver#233]
When clicking on "Hide Data" in Markers section the parts of displayed information start to twitch erratically (many times per second) when main app window maximized full screen - the graphs (ie 3 selected) several pixels left-right direction and the "Reference sweep" part on the left several pixels up/down direction.
No erratic twitching when the marker data are shown.
No erratic twitching when main app window made smaller than maximized.
It does jerk with or without nanovna-h4 connected.
Nanovna-Saver 0.3.4
Win 10 64bits, 1920x1080 pixels display

**Comment by igor-m** [comment]
The picture jerks when ie.:
a) the main app window is maximized
a) there are 3 graphs selected
b) one of them is Polar Plot or Smith Chart
![Erratic jerking](https://user-images.githubusercontent.com/7240123/87146164-d0b56880-c2aa-11ea-908a-5a7fa4e2a7a2.PNG)

**Comment by RandMental** [comment]
I can not duplicate this

**Comment by igor-m** [comment]
Here an example in .avi
[Erratic display.zip](https://github.com/NanoVNA-Saver/nanovna-saver/files/4902709/Erratic.display.zip)
