### ISSUE TITLE
Calibration buttons do not provide valid calibration data

### ISSUE THREAD

**Issue by igor-m** [NanoVNA-Saver/nanovna-saver#238]
While calibrating and clicking at the "Short" "Load" "Open" buttons (Calibrate section) the action does not provide calibration procedure and valid data. 

The calibration procedure with valid output data works via "Calibration assistant" only.

saver v0.3.4, v0.3.5

**Comment by zarath** [comment]
should be fixed in v0.3.6-rc

**Comment by igor-m** [comment]
Nope, it does nothing here in 036rc2..

**Comment by zarath** [comment]
have you pushed the buttons hard enough? ;-)

**Comment by PA3CCE** [comment]
@ Zarath.... Hi Zarath did you delete my issues abt aborting NanoVNA-Saver at start from scrath and abt nthe Markers ? This morning I still found some issues.

**Comment by PA3CCE** [comment]
@Zarath.... I downloaded and installed rc2, ran it and it performed vy well, so this is the reason why you closed my previous issues I suppose..... At first glance I saw that, though I did not set any markers, The markers are still filled with data of the Start frequency, and that my **scrolling** the **mousewheel** problem was'nt solved..... I keep on testing. ...regards

**Comment by PA3CCE** [comment]
I forgot to attach the debug.txt file.
[test-rc2.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4931764/test-rc2.txt)

**Comment by zarath** [comment]
> @zarath.... I downloaded and installed rc2, ran it and it performed vy well, so this is the reason why you closed my previous issues I suppose..... At first glance I saw that, though I did not set any markers, The markers are still filled with data of the Start frequency, and that my **scrolling** the **mousewheel** problem was'nt solved..... I keep on testing. ...regards

Please make a new bug report, I cannot track a thounsend different bugs in one thread....

**Comment by zarath** [comment]
Cannot reproduce, see here:


https://youtu.be/G3kqqY8eDIU

**Comment by igor-m** [comment]
After SOL I get error when applying calibration
![err](https://user-images.githubusercontent.com/7240123/87724464-cff56880-c7bb-11ea-9075-2923f7055f06.PNG)

**Comment by zarath** [comment]
Pushing the short load.. button takes the last runned sweep as  data. so as in my video you have to connect short, make a single sweep and than press short button and so on. Point count is shown immediately

**Comment by igor-m** [comment]
Well, then this app is not intended for users with my way of thinking.. :) 
I expected 
1. I connect short
2. push the Short button
3. it makes a sweep
4. it writes "Set 2010 points"
and so on..

**Comment by zarath** [comment]
That's why this is the experts option. Kidding. A user handbook would be nice..
