### ISSUE TITLE
Touchstone Export File Format

### ISSUE THREAD

**Issue by Roger-Need** [NanoVNA-Saver/nanovna-saver#245]
I am using NanoVNA Saver 0.3.4 and found a bug with Touchstone file export.   There is a formatting bug that prevents the file from being loaded into other programs.  It has to do with the Option Line.  The frequency is expressed in HZ and that is not valid.  It must be Hz  (z is lower case).  This seems to have changed since 0.2.2 which worked OK.  

I attached an excerpt from the Touchstone specification below...
![Touchstone](https://user-images.githubusercontent.com/68256449/87366030-8d6a2c80-c52c-11ea-8d00-eb87c1775cdd.PNG)

**Comment by zarath** [comment]
What about the first line in the 1.1 Touchstone definition?

![Screenshot_20200714_075638](https://user-images.githubusercontent.com/912565/87389792-bed40e00-c5a7-11ea-8780-803186ea410e.png)

Touchstone is defined as case insensitive.

What program is complaining about the option line?

**Comment by Roger-Need** [comment]
The program is AntScope2.   [https://rigexpert.com/products/software/antscope2/](url)

This program developed by RigExpert now supports the NanoVNA-H and there is a planned release for other NanoVNA models.   It is beneficial to be able to exchange .s1p files with this program because it supports multiple S11 traces, de-embedding cable feedlines, conversion to other system impedances and several other useful features.  

I can manually go in and edit HZ to Hz and it works but other users will probably not know this and just assume a file incompatibility.

**Comment by Roger-Need** [comment]
Oops - closed by mistake....

**Comment by zarath** [comment]
see https://github.com/rigexpert/AntScope2/issues/6

**Comment by Roger-Need** [comment]
Zarath - I see you posted this issue on the AntScope2 github.  That will not help solve the problem.  RigExpert basically just ignore issues on github and are not very responsive to feedback on their own groups.io forum.  

 Is it a big change to put it back the way it used to be with "Hz" in 0.2.2?

**Comment by zarath** [comment]
It could break imports in other broken software....

Fun fact: RigExpert use scanf and strcmp with qt and c++ in 2020!!!!

**Comment by Roger-Need** [comment]
I have edited touchstone.py to output Hz and built an executable version of NanoSaver 0.3.4.  It now exports files that are importable by other popular programs (AntScope2, AppCad, Filpal, VNWA, NanoVNA Mod V3, NanoVNA#, NanoVNA Partner).  Since this issue is now marked "invalid" I will fork NanoVNA Saver to another github and release versions from there for those interested.   A link to a Windows executable should be available on groups.io and Facebook in a few days...

Roger
