### ISSUE TITLE
Center and Span Frequency numbers do not fit fields

### ISSUE THREAD

**Issue by igor-m** [NanoVNA-Saver/nanovna-saver#251]
Wrong Center and Span Frequency in 036-rc info shown, see below (H4 0845fw).
![Wrong Center and Span Frequency 2](https://user-images.githubusercontent.com/7240123/87477748-ec14d080-c628-11ea-85eb-ed5d1e21c3c3.PNG)

![Wrong Center and Span Frequency](https://user-images.githubusercontent.com/7240123/87476951-8ecc4f80-c627-11ea-873d-d47d8c98135e.PNG)

**Comment by zarath** [comment]
Wrong or just not fitting?

**Comment by zarath** [comment]
I assume there is a 1.899Ghz span

**Comment by igor-m** [comment]
It could be the Span does not fit, but the Center is definitely not good..

**Comment by zarath** [comment]
Have you clicked in and used cursor keys to scroll left and right

**Comment by zarath** [comment]
There are anti alias artifacts that suggest that the 0 is not the first digit

**Comment by igor-m** [comment]
You are right it does not fit..
![Not fitting](https://user-images.githubusercontent.com/7240123/87478377-f71c3080-c629-11ea-9d16-8bf2598db4ed.PNG)

**Comment by zarath** [comment]
950,025MHz would be center... thus 0025 looks plausible

**Comment by igor-m** [comment]
That is because I do not own a 4k display..

**Comment by zarath** [comment]
It was annoying me long time ago, but me PR was rejected.
I'll look for a better Input field arrangements in future. But definitely nothing to go in 0.3.6... Gui quirks are so depending on individual settings. And as long as markers and scales are right I didn't bother too much.

Also it's not a 0.3.6 introduced bug

**Comment by igor-m** [comment]
Simply round to 3 digits after decimal point, the high precision of that information is not critical imho.

**Comment by zarath** [comment]
This is a duplicate of #154
