### ISSUE TITLE
Data outside the Smith Chart

### ISSUE THREAD

**Issue by igor-m** [NanoVNA-Saver/nanovna-saver#258]
Both nanovna meter as well as the nanovna-saver can depict the data outside the Smith Chart.
I asked on that issue (groups.io) and got that it depends on the calibration (quality of the cal set, or changes made after calibration, ie. different cable, etc).
I think technically it could be pretty easy to create a mess with the calibration and the measurement, the Smith Chart should not show data outside its border, however (as the space outside the SC border "does not exist").
I would suggest either to
a) not show such outliers, or,
b) place the outliers at the SC border (and color them RED, for example).
Below an example.
![Data outside Smith Chart](https://user-images.githubusercontent.com/7240123/87591944-63119e00-c6e9-11ea-9664-794643562ee0.PNG)

**Comment by zarath** [comment]
It's just data behind infinity... .it falls of the border of the earth disk.

But I'm uncertain if this values, which are created by cable, plug, calibration inaccuracies should be suppressed.

**Comment by igor-m** [comment]
My math knowledge gets pretty rusty, but I am pretty confident that "with _any_ values of the calibration data the measurement results will _always_ be inside the SC space".

**Comment by igor-m** [comment]
FYI - "3D Smith Chart" tool -  https://www.microwavejournal.com/articles/33830-d-smith-chart-tool-is-now-free-to-all-students

**Comment by satfan52** [comment]
Normally of the calibration is done with a good calibration kit,this should not be not an issue in practice. 

The other case that I have encountered is a reflexion coeficient greater than 1 and a negative real value of an input impedance.  This was when I measured an unstable amplifier that tended to oscilliate at some frequencies, but that measurement was entirely normal and to be expected with unstable active device

**Comment by igor-m** [comment]
The Smith chart cannot show data outside its border. It is like an o'scope screen..  :)
Imagine yourself an oscilloscope screen - you may do whatever you want with its settings, probes calibration, etc., it will not show the traces outside its screen.

**Comment by satfan52** [comment]
Actually it can with an unstable amplifier but not with passive devices (filters etc..). Check the literature on stability factors and stability circles which all have to do with reflection coeficient bigger than 1 and falling outside the smithchart. Myself, I have experienced that some amplifiers that I build/test can  exhibit a reflection coefficient bigger than 1 at low frequencies, the nanovna is not wrong.
