### ISSUE TITLE
Calibration - Offset Delay - Setting  

### ISSUE THREAD

**Issue by RandMental** [NanoVNA-Saver/nanovna-saver#259]
Saver V0.3.6 RCx uses a decial point for values, but the Offset Delay in the Calibration dialogue  use a decimnal comma.

![image](https://user-images.githubusercontent.com/6272455/87679406-6d30ac80-c77c-11ea-92d0-4d79d16f211f.png)

**Comment by zarath** [comment]
looks like languages settings in qt...

Nothing that I've ever touched... First occourance in 0.3.6????

**Comment by zarath** [comment]
Depends on LC_NUMERIC environment in linux ... with German I get a comma unset I get a point

**Comment by zarath** [comment]
Funny, in South Africa both decimal separators are possible...

https://en.wikipedia.org/wiki/Decimal_separator#Countries_using_decimal_comma

So I think a recommendation to use a US or GB locale with nanovna-saver to get a consistent view ...
