### ISSUE TITLE
Save ( and read ) additional info in export file

### ISSUE THREAD

**Issue by gaionim** [NanoVNA-Saver/nanovna-saver#26]
It would be useful to save information such as used calibration file (and more) in addition to a free description eg
"un-un 49: 1 150pF"
or
"un-un 49: 1 without capacitor"
in order to facilitate comparisons.

See http://na.support.keysight.com/plts/help/WebHelp/FilePrint/SnP_File_Format.htm

73

**Comment by mihtjel** [comment]
Yeah, definitely! I'm adding it, but I want to read comments from Touchstone files first and find a way to display them, before I add writing them.
