### ISSUE TITLE
NanoVNA-Saver 3.6 rc2 shows markerdata when NOT set for

### ISSUE THREAD

**Issue by PA3CCE** [NanoVNA-Saver/nanovna-saver#260]
**Describe the bug**

**To Reproduce**
1. Start NanoVNA-Saver.
2. Click on "Connect to device".
3. NanoVNA-Saver shows data from stopfrequency in Markerdata-area (Incidently I have seen data from startfrequency).
4. See error in attached picture
5. Debug file is attached

![Schermopname (8)](https://user-images.githubusercontent.com/14205041/87712958-b9461600-c7a9-11ea-8a43-48efd50e8760.png)

[dbug-rc2-2.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4933703/dbug-rc2-2.txt)

**Expected behavior**
No data in markerdata-area

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows10 Home edition.
 - Python version: NA
 - NanoVNA-Saver version: 3.6 rc2

**Comment by igor-m** [comment]
That is not a bug, rather a feature - like default settings with empty Marker's fields.
With empty fields it would be nice to have the markers filled with frequencies like, for example, in case of 5 markers
f=(stop-start)/4
M1 = start
M2 = M1 + f
M3 = M2 + f
M4 = M3 + f
M5 = stop

**Comment by PA3CCE** [comment]
OK, I agree, but at the moment they are filled with all the same data. 5 markers is maximum, otherwise window is oversized.

**Comment by PA3CCE** [comment]
PLease why Zarach ?

**Comment by zarath** [comment]
because illegal values in enabled markers causes more trouble and lead to more complex and therefore more error prone code

**Comment by PA3CCE** [comment]
OK, then leave the areas open, please.

**Comment by PA3CCE** [comment]
Or disable the markers.
