### ISSUE TITLE
Default bandwidth setting

### ISSUE THREAD

**Issue by PA3CCE** [NanoVNA-Saver/nanovna-saver#262]
**Is your feature request related to a problem? Please describe.**

NanoVNA-Saver starts with bandwidth default set to 1000 Hz, after "Connect to device"  it resets to **2000** **Hz,** this is the **least** accurate setting.

A clear and concise description of what you want to : 

NanoVNA-Saver bandwidth after "Connect to divice"  sets to last used bandwidth.

**Comment by zarath** [comment]
would be possible in future. But it was concise to start with lowest bandwidth to get a first sweep as fast as possible.

With ttrftech's firmware its even impossible to get the current bandwidth from the device
