### ISSUE TITLE
Implement basic de-embedding functionality 

### ISSUE THREAD

**Issue by satfan52** [NanoVNA-Saver/nanovna-saver#266]
**Important Note:** This change request only makes sense to implement if  #203  is implemented as a prerequisite.  The reason is that deembedding requires to be able to work with the 4 S parameters of a two port device and not only with S11 and S21. So implementing # 203 is a prerequisite so nanovna-saver can  generate fully populated touchstone S2P files with the 4 S parameters (S11, S21, S12 and S22) and not only with S11 and S21.

**Context of the request**

It is always best from a technical/electrical point of view to  measure a DUT with the VNA directly connected to it and to put the reference/calibration planes at the DUT interfaces.

However, sometimes for practical and pragmatic reasons it is not feasible or even desirable to do a direct DUT measurement. For instance, the DUT may be challenging to physically access to measure it (like an antenna at the end of a long feedline or a chip on a PCB)  or it may be dangerous or risky to measure it directly ( like in the case of an amplifier for instance). In some situations it is also easier to proceed to an indirect measurement, for instance to avoid having to un-solder components on a PCB to directly measure a DUT (assuming  spares of those components are available for making separate measurements). 

Typically the situation can be seen as the following; "A Target 2 port DUT" is connected to a front-end on its input ( "network 1") and to a back-end on its output (network2). The two "networks" sit between the DUT and the nanovna and the challenge is to determine the 4 DUT S parameters  by measuring the whole chain **"network 1- DUT -network 2**" as well as by measuring **"network 1"** and **"network 2"** separately. 

If the DUT is only 1 port like an antenna, then there is no network 2 of course, only network 1. The challenge is to deembed the S11 parameters of the DUT.

Network 1 and network 2 can be matching elements (microstrips, coax stubs, L networks etc..), couplers, rf-transformers, connectors, small amplifiers, test fixtures, electric long and potentially losy feedlines etc.... etc...

Of course if "network 1" or "network 2" have more than 20dB loss this approach will not work well for obvious reasons.  
  
**Procedure:** 

As explained above, instead of measuring the DUT directly, the idea is to measure the "DUT+the two networks"  as well as each "network" separately. Based on those 3 measurements it is possible to mathematically determine the DUT S parameters

measurement 1 (S matrix 1):  network 1-DUT-network2 (no network 2 is the DUT is 1 port like an antenna)
measurement 2 (S matrix 2):  network 1 only
measurement 3 (S matrix 3):  network 2 only (no applicable to 1 port DUT like an antenna)

The process of calculating the DUT parameters based on these 3 measurements requires a bit of math.

1. Converting the 3 S matrices  (S1,S2, S3)  into T matrices  (T1,T2,T3). 

2. Inverting  T2 and of T3 matrices

3. Calculating the T maxtrix of the DUT : T_DUT= INV(T2) * T1 * INV(T3) 

4.  Of course what works for a two port DUT like a filter etc.. also works for a 1 port DUT like an antenna. In that case there is just no S3 and no T2 Matrixes. T_DUT=INV(T2)*T1  

5. Converting the T matrix of the DUT into an S matrix to get the 4 deembedded S parameters of the 2 port DUT 
(only the deembedded S11 parameter if is a 1 port DUT) 

There is nothing new, all of this is very well known and documented at length on the Internet, notably by Keysight and ADI.

https://www.keysight.com/be/en/assets/7018-06806/application-notes/5980-2784.pdf
http://na.support.keysight.com/vna/help/latest/S3_Cals/Fixturing.htm#deembed

**Description of the change that is requested**

It is proposed to offer the possibility to import** via the File Menu**, as touchstone formatted SP2 files, the S2 and S3 files corresponding to network 1 and network 2. It is also proposed to add in that same File menu a  "check box"  to activate or de-activate the deembedding function. If the checkbox is enabled, nanovna-saver would do the de-embedding calculation explained above at every sweep and display the deembedded S11, S21 parameters via the usual interfaces (no changes to display traces, markers , etc..). When doing the S2P export, the 4 S parameters of the DUT would of course be exported and not only the displayed deembedded S11 and S21 parameters. For a one port DUT the exported S1P file should contain the deembeded S11. 

To summarize,  change needed to the GUI FILE interface are the following :
"import S2P files as network 1"
"import S2P files as network 2"
"check-box to enable/disable deembedding"
+
when exporting the S2P file (for analysing dembedded data of a 2 port DUT like a filter or a balun ),  if the check box is enabled, the 4 deembeded S parameters should populate the exported touchstone S2P file and not only the dembeded S21 and S11.
+
when exporting the S1P file (for  analyzing deembedded data of  a 1 port DUT like an antenna)  if the check box is enabled, the deembeded S11 parameters should populate the exported touchstone S1P file_**

**Constraint**
This implies that the S2 and S3 files imported must be full two port ones populated with the 4 S parameters. Generating such  a full two port files at requires therefore #203  to be implemented as a pre-requisite. 

**Benefit for the user**

This would give owners of a nanovna device costing less than 100 USD and using open source software access to the same sophisticated functionalities (though with less convenience I agree) than ultra expensive vnas used in combination with proprietary software (also not cheap) such as  Mathlab, ADS etc.

**Comment by igor-m** [comment]
I've been coping with a bare wire antenna measurement.. Such a measurement would require de-embedding, imho.
Btw, a "plug-in" nano-saver functionality would be "nice to have", thus people would be able to write special procedures and math.

**Comment by satfan52** [comment]
In the mean time, the SIMSMITH software has been upgrade to provide this functionality, **so if the 4 S parameters can be exported in an S2P file it is actually OK**, it makes this change request much less urgent.   Some functionality is required to captre S12, S21 but also S22 and S12 (after reversing the device) and the producing a fully populated S2P file with the 4 parameters

**Comment by human890209** [comment]
> 

How to do this with SimSmith( current version: SimNEC 1.2)?

**Comment by human890209** [comment]
> In the mean time, the SIMSMITH software has been upgrade to provide this functionality, **so if the 4 S parameters can be exported in an S2P file it is actually OK**, it makes this change request much less urgent. Some functionality is required to captre S12, S21 but also S22 and S12 (after reversing the device under test) and the producing a fully populated S2P file with the 4 parameters

How to do this with SimSmith( current version: SimNEC 1.2)?

**Comment by Ho-Ro** [comment]
Please check if also #203 has relevance.

**Comment by andreamerello** [comment]
+1 at least for 1port measurements (s11)
