### ISSUE TITLE
Marker 2 colorsetting not possible

### ISSUE THREAD

**Issue by PA3CCE** [NanoVNA-Saver/nanovna-saver#267]
**Describe the bug**
Marker 2 color can't be set..

**To Reproduce**
1. Click on color square of marker 2 in main window.
2. Set for color to be used in the color selection window.
3. Click "ÖK".
4. New color is not set.

**Expected behavior**
New color for marker 2 is set.

**System** :
OS : Windows 10 Home edition.
Device : NanoVNA -H4 firmware 0.9.3.4 by DiSlord.
NanoVNA-SWaver version 3.6

**Comment by zarath** [comment]
Unreproducable on my machine

**Comment by PA3CCE** [comment]
Tried this again also, the color square still is not filled with the selected collor.

**Comment by PA3CCE** [comment]
OK, Started NanoVNA-Saver 3.6 connected it to the -H4 and first tried to set marker 2  color, no success then  tried to set it on the trace , no result either, maybe because there is not set a color ?..... Hope you find something in the debug_Marker_2 file
[debug_Marker_2.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4953063/debug_Marker_2.txt)

**Comment by PA3CCE** [comment]
@Zarach Problem sol;ved, please see my last comment in **Marker 2 does not show in display**
