### ISSUE TITLE
MJissing things in some displays

### ISSUE THREAD

**Issue by PA3CCE** [NanoVNA-Saver/nanovna-saver#272]
**Describe the bug**
In some S11 and S21 displays some items are missing..

**To Reproduce**
1. Load and start NanoVNA-Saver 3.6
2. Click on  "Display setup" and add one or more markers.
3. Run a  sweep.
4. Press "Display setup ..."
5. Select a  "Displayed charts / **Real & Imaginary" "**
6. The SWR marker line(s) is/are not shown, shall be there between 0 and -10 db lines.
7. Press "Display setup...".
8.  Select a "Displayed charts/ **S11 Real/Ímaginary".**
9. In the respective chart **no** color indication is given **what** trace is **what** color.
10. Press "Display Setup".
11. Select a "Displayed charts/ **S21 Real/Imaginary"** .
12 .In the respective chart **no** color indication is given **what** trace is **what** color.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows10 Home edition.
 - Python version:  NA
 - NanoVNA-Saver version:  0.3.6
![Schermopname (12)](https://user-images.githubusercontent.com/14205041/87940446-e2acbd80-ca99-11ea-83f1-a936f7f2c86d.png)

**Comment by zarath** [comment]
Also not been in v0.2.x versions. an older bug

**Comment by PA3CCE** [comment]
About version 0.2.x, yes I know, but imho these things must be there.

**Comment by zarath** [comment]
I've just remove the reference to 3.6 as it is existing on all versions. So I don't have to do researching if I introduced the bug in my recent code changes.

**Comment by PA3CCE** [comment]
ok,  Iunderstand
