### ISSUE TITLE
NanoVNA crashes or wrong data displayed after first start of Nanovna V2

### ISSUE THREAD

**Issue by ok1vaw** [NanoVNA-Saver/nanovna-saver#277]
After connecting NanoVNA V2 (without battery inside) to USB and starting NanoVNA Saver the program crashes or shows incorrect values. It needs to reconnected and connected again, after that it works. Tested with different USB2 and USB3 port and different cables, appears on version 034, 035, 036, USB2 direct to PC or from HUB with power supply. Debugging info attached and screenshot with strange measurement added.
[debug_instability.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4969561/debug_instability.txt)
[debug.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4969562/debug.txt)
[debug_instability.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/4969568/debug_instability.txt)
![wrong display after start](https://user-images.githubusercontent.com/6250023/88348588-216a9e00-cd4e-11ea-94be-9a103299f798.jpg)

**Comment by zarath** [comment]
can you try v0.3.7-rc03 or newer

**Comment by ok1vaw** [comment]
Still the same, I have even tried a second USB PCI card with NEC chip (AXAGO PCIU-60), but it behaves in the same way.  Now I test it with the RC05.

**Comment by ok1vaw** [comment]
With installing the Li-Ion battery inside, this problem with start disappeared.

**Comment by Mike4U** [comment]
See #322  at Mike4U
