### ISSUE TITLE
Popup charts - use a different position for a new popup

### ISSUE THREAD

**Issue by igor-m** [NanoVNA-Saver/nanovna-saver#278]
While popping up charts the popped up :) charts group at the same position, thus you always see only one chart (the latest).
Do shift the position of each newly pop-upped chart a little bit such you see them all.
037-pre

![Popping up the charts at shifted positions](https://user-images.githubusercontent.com/7240123/88368267-f99b2a80-cd8d-11ea-839e-67fa33541907.PNG)

**Comment by JulyJim** [comment]
Just a comment 
I grew up with Microsoft MFC and like their terminology / naming conventions of GUI "components".
What you describing would be called "cascading views".
Similar GUI arrangement of multiple views under "one umbrella " woudl be "tiled views".
They often add tab to the view so can select the view using visible tabs.
