### ISSUE TITLE
Markers - complete values not visible

### ISSUE THREAD

**Issue by igor-m** [NanoVNA-Saver/nanovna-saver#279]
The Markers do not show complete values.
For example see below the Impedance (real part missing).
037pre
![Marker data issue](https://user-images.githubusercontent.com/7240123/88371845-1c7d0d00-cd95-11ea-8c67-65ee9f466b4f.PNG)

**Comment by zarath** [comment]
This happens if "real" part is below zero.
Showing negative resistance could also be irritating

**Comment by igor-m** [comment]
OK, then I would suggest make it less irritating with showing

-R+345j 

for example, indicating the resistance is negative.

**Comment by zarath** [comment]
Don't feel so much better with the R ... perhaps sometime in future there will be handbook which mention that dash ...
