### ISSUE TITLE
v0.3.7-pre02 (32-bit)

### ISSUE THREAD

**Issue by RexAlfes** [NanoVNA-Saver/nanovna-saver#284]
I use a Windows Tablet in the field. It is Windows 10 but only supports 32bit. Can we get a 32bit version of NanoVNA-Saver?

**Comment by zarath** [comment]
If one find out, how to create 32Bit binaries with github actions...

**Comment by zarath** [comment]
But it's always possible to do a source installation. If instructions in README.md aren't sufficient for you, the is a thread in groups.io regarding this topic.

**Comment by zarath** [comment]
Can anyone try:

https://github.com/NanoVNA-Saver/nanovna-saver/actions/runs/191035033

**Comment by zarath** [comment]
Fixed in 0.3.7
