### ISSUE TITLE
Markers miss info and green bar issue 037-pre1

### ISSUE THREAD

**Issue by igor-m** [NanoVNA-Saver/nanovna-saver#285]
While running 037-pre01 (see below) in continous sweep mode Segments=1 (BW 2kHz, 201p, latest dislord's 1.0.2, H4) the Marker (ie Marker1) does not show all info, and the sweep bar does not sweep (stays 100% green).
![Marker and green sweep bar issue](https://user-images.githubusercontent.com/7240123/88479623-cf459a80-cf50-11ea-8464-b6085ec61ac4.PNG)

**Comment by zarath** [comment]
strange..

**Comment by igor-m** [comment]
The Marker's information should update only when the sweep finishes, imho.
It seems the Marker's information updates _during_ the sweep process, thus it messes up sometimes (or always)..

**Comment by zarath** [comment]
I would be better if a marker updates after each scanned segment
