### ISSUE TITLE
How to run the Darwin binary package with Library Validation switched on?

### ISSUE THREAD

**Issue by Toontje** [NanoVNA-Saver/nanovna-saver#288]
I downloaded NanoVNASaver.macos-latest and decompressed it. When i run nano-saver i get "Unverified Developer" pop-ups for all dylib and so files.

How to get around this?

https://github.com/NanoVNA-Saver/nanovna-saver/releases/download/v0.3.6/NanoVNASaver.macos-latest.zip on OSX Catalina.

**Comment by peterbmarks** [comment]
In the unzipped directory, remove the quarantine extended attribute with:
xattr -rd com.apple.quarantine .

**Comment by zarath** [comment]
I have updated the installation hints in the releases description.
