### ISSUE TITLE
V0.3.7-Pre01 

### ISSUE THREAD

**Issue by RandMental** [NanoVNA-Saver/nanovna-saver#292]
**Describe the bug / Change **
The Marker window can not be scrolled to the right far enough to show both columns of Marker data.

There is scroll bar at the bottom, but it is no practical to scroll every time, rather I would want to size it without a Scroll bar and save the layout.   This is with 3 graphs horizontally enabled, e.g. 6 in total  

It obviously depends on the Monitor screen size and aspect ratio, but I believe it would affect most users with the current sizing applied. 

![Saver 037pre02](https://user-images.githubusercontent.com/6272455/88694325-a8c66180-d100-11ea-89d7-d909976a9fb7.png)

**Comment by zarath** [comment]
Perhaps one should start with just 4 instead of 6 charts
