### ISSUE TITLE
Missing last frequency (=Stop frequency) in Export of S1P/S2P 

### ISSUE THREAD

**Issue by MaxCrt** [NanoVNA-Saver/nanovna-saver#300]
The Export of S1P/S2P data is missing of last frequency measurement, that is the "Stop frequency"

1) Make a S11 measurement
2) Go to "Files..."
3) Select "Save 1-port file"
4) In the exported S1P file, the last measurement of frequency range (=Stop frequency) is missing

**Screenshots**

OS: Windows 7 professional
NanoVNA-Saver version: 0.36

[S1P 50k-30M.zip](https://github.com/NanoVNA-Saver/nanovna-saver/files/5000469/S1P.50k-30M.zip)

**Comment by zarath** [comment]
This is not a bug. It a limitation of Integers.

You have done a sweep with 10 segments á 101 Points. 
Therefore you have 1010 frequencies in your s1p file.
