### ISSUE TITLE
037-rc1 offers in Manage 11, 51 and 101 points only (missing 201p offer)

### ISSUE THREAD

**Issue by igor-m** [NanoVNA-Saver/nanovna-saver#301]
The 037-rc1 offers (in Manage) 
11
51
101
data points.

**Comment by zarath** [comment]
And what is the issue with it?

**Comment by igor-m** [comment]
201 points is missing.

When H4 is set with 201 points I get after initial sweep:

2020-07-30 19:35:45,872 - NanoVNASaver.SweepWorker - ERROR - division by zero
Traceback (most recent call last):
  File "C:\Users\smith\MyCode\HAMradio\NanoVNASaver\nanovna-saver\nanovna-saver\NanoVNASaver\SweepWorker.py", line 80, in run
    self._run()
  File "C:\Users\smith\MyCode\HAMradio\NanoVNASaver\nanovna-saver\nanovna-saver\NanoVNASaver\SweepWorker.py", line 122, in _run
    start, stop, averages)
  File "C:\Users\smith\MyCode\HAMradio\NanoVNASaver\nanovna-saver\nanovna-saver\NanoVNASaver\SweepWorker.py", line 250, in readAveragedSegment
    values11 = np.average(values11, 0).tolist()
  File "<__array_function__ internals>", line 6, in average
  File "C:\Users\smith\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\function_base.py", line 381, in average
    scl = avg.dtype.type(a.size/avg.size)
ZeroDivisionError: division by zero

**Comment by zarath** [comment]
Can I have the debug file?

**Comment by igor-m** [comment]
[debug.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/5002962/debug.txt)

**Comment by zarath** [comment]
Can you look if you have data validation enabled?
If so, can you try to run without?

**Comment by igor-m** [comment]
Validation is/was off. Freshly calibrated.
Using dislord's H4 commit from 17.7. (he is not publishing sources for 1.0.x).

**Comment by zarath** [comment]
That's not so weird, I decided to get 101 point initially with lowest bandwdth.

Unfortunately I cannot read out bandwidth, so i set it to the lowest, to get a fast first result. I think it is sane, as if one has bw set to 10Hz, it would take over a minute  (or two with 201 points) for the first response...

rc02 should give an error message now, but don't crash... also debug message about read out frequency length is now in debug file, because in your crash s11 and s21 data was equally long, so frequencies was possibly wrong.

**Comment by igor-m** [comment]
I calibrated the H4 again (save0, 50k-900M, BW1000, 201p)
Same error div by zero after first sweep with rc02.

**Comment by zarath** [comment]
F*ck. But please the new debug filr

**Comment by igor-m** [comment]
[debug.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/5003247/debug.txt)

**Comment by zarath** [comment]
I'll try to fix it tomorrow,

**Comment by igor-m** [comment]
This is a scan made via terminal, after power off/on H4

ch> scan 50000 900000000 101 0b110
0.000081036 0.000001460 -0.000003710 -0.000005772
0.000080605 -0.000021275 -0.000004053 0.000007163
0.000060820 -0.000070426 -0.000020719 -0.000007191
0.000089447 -0.000079433 -0.000006488 0.000007368
0.000073057 -0.000100548 -0.000020569 -0.000011065
0.000100162 -0.000118306 -0.000028264 -0.000010499
0.000080241 -0.000135901 -0.000022139 -0.000000176
0.000081200 -0.000149924 -0.000038091 -0.000007455
0.000110806 -0.000158060 -0.000059047 -0.000004801
0.000102303 -0.000190099 -0.000019993 0.000008938
0.000123966 -0.000217492 -0.000027036 0.000016083
0.000140627 -0.000240741 -0.000049206 0.000028306
0.000115597 -0.000293970 -0.000007381 0.000047120
0.000193984 -0.000268245 0.000025396 0.000108076
0.000181298 -0.000321943 0.000030500 0.000125400
0.000214941 -0.000333792 0.000038063 0.000116281
0.000214151 -0.000337594 0.000028986 0.000107140
0.000218665 -0.000357857 0.000063418 0.000156341
0.000276070 -0.000334074 0.000092082 0.000204765
0.000325602 -0.000376786 0.000130167 0.000209051
0.000286336 -0.000440135 0.000144687 0.000126592
0.000313443 -0.000432650 0.000250564 0.000169574
0.000319413 -0.000444752 0.000300635 0.000210860
0.000298908 -0.000503633 0.000365491 0.000222531
0.000307254 -0.000507538 0.000443857 0.000247890
0.000185184 -0.000553137 0.000510636 0.000249889
-0.000063140 -0.000402665 0.000618942 0.000223222
-0.000043137 0.000539141 0.000689223 0.000182204
0.001044676 0.000358541 0.000734252 0.000151028
0.001285859 -0.000233044 0.000721668 0.000084956
0.001104448 -0.000552238 0.000603109 -0.000000702
0.000954830 -0.000694450 0.000546570 -0.000100433
0.000777260 -0.000651158 0.000513809 -0.000210013
0.000723492 -0.000618600 0.000483248 -0.000287994
0.000790100 -0.000550599 0.000010638 -0.000189321
0.000835480 -0.000637631 0.000155368 -0.000345919
0.000824349 -0.000564786 0.000250756 -0.000342780
0.000849563 -0.000506578 0.000160717 -0.000403431
0.000749461 -0.000476000 0.000210745 -0.000334115
0.000760052 -0.000453037 0.000133266 -0.000343916
0.000988762 -0.000223654 -0.000014153 -0.000430359
0.000952472 -0.000392074 0.000001102 -0.000390559
0.000965400 -0.000413903 -0.000010240 -0.000332711
0.000935344 -0.000335260 -0.000090021 -0.000318434
0.001361017 -0.000728005 -0.000057343 -0.000337390
0.001069533 -0.000210195 0.000033439 -0.000307785
0.001004746 -0.000386871 -0.000064461 -0.000345894
0.000826911 -0.000259441 -0.000067305 -0.000372440
0.000771280 -0.000279083 -0.000218762 -0.000402001
0.000983485 -0.000147177 -0.000235917 -0.000465647
0.000743074 -0.000202332 -0.000228590 -0.000387141
0.000783516 0.000103337 -0.000330982 -0.000290335
0.000763994 -0.000114565 -0.000313196 -0.000294419
0.000929704 0.000190549 -0.000342077 -0.000256300
0.001113876 0.000203153 -0.000269012 -0.000240378
0.000846723 -0.000015414 -0.000294593 -0.000175366
0.000783127 0.000180657 -0.000159587 -0.000066134
0.001022368 -0.000593121 -0.000063722 -0.000012024
0.000962320 0.000114259 -0.000023415 -0.000081836
0.000857457 0.000129722 0.000065995 -0.000318775
0.000576778 0.000072526 -0.000018697 -0.000678074
0.000740932 0.000294859 0.000036003 -0.000768083
0.000598392 0.000006614 -0.000338703 -0.000705579
0.000813648 0.000212541 -0.000403555 -0.000655117
0.000701247 0.000281021 -0.000711068 -0.000588638
0.000711158 0.000857987 -0.000739817 -0.000293366
0.000696677 0.000275233 -0.001033396 -0.000326301
0.000731584 0.000223451 -0.001045140 -0.000121323
0.000557548 0.000437348 -0.001185987 0.000174352
0.000772570 0.000432013 -0.001121060 0.000284860
0.000629674 0.000487748 -0.001299280 0.000611498
0.000493561 0.000231212 -0.001151342 0.000683190
0.000603071 0.000128442 -0.001043921 0.000764597
0.000698930 -0.000070742 -0.001201311 0.000882712
0.000332168 -0.000048147 -0.001046305 0.001037218
0.000293715 0.000225549 -0.001190835 0.001216466
0.000325930 0.000268564 -0.001072813 0.001292295
0.000598351 0.000369068 -0.001051426 0.001495677
0.000610642 0.000123471 -0.000959237 0.001816770
0.000192754 0.000100796 -0.000815451 0.001938605
0.000203989 0.000066887 -0.000626134 0.002003333
0.000438869 -0.000003382 -0.000478470 0.002261878
0.000250124 0.000209618 -0.000384239 0.002462666
0.000257060 0.000166685 -0.000169574 0.002527590
0.000242197 -0.000113916 -0.000104477 0.002557712
0.000401695 -0.000088892 0.000240021 0.002680505
0.000455128 -0.000121178 0.000255253 0.002778508
0.000308784 -0.000161992 0.000557478 0.002827261
0.000316636 -0.000012911 0.000545513 0.002814698
0.000465738 -0.000083605 0.000911079 0.002832326
0.000123494 0.000108303 0.001000896 0.002778204
0.000646628 -0.000504321 0.001377161 0.003023308
0.000334240 -0.000097265 0.001484421 0.002838409
0.000598639 0.000015078 0.001580588 0.002731942
0.000271397 -0.000303173 0.001622291 0.002861861
0.000342084 -0.000164162 0.001628089 0.002743381
0.000716726 -0.000563117 0.001941208 0.002830456
0.000608337 -0.000021936 0.002058653 0.002628744
0.000784566 -0.000449325 0.002378519 0.002620347
0.000446208 0.000029589 0.002567527 0.002215071
0.000403097 -0.000332913 0.002663263 0.001963991
ch>

**Comment by igor-m** [comment]
It shoots Divide by zero only after the first sweep after the powering off/on the H4.
Afterwards it works (I can connect/disconnect and it works)..

**Comment by igor-m** [comment]
Hmm, it looks like the change of the VERSION string in the H4 source introduces the DIV by 0 problem after the initial poer up of the H4.
Still Manage does not offer 201p.

**Comment by zarath** [comment]
I  assume every current H4 can do 201 datapoints now.

see rc03

**Comment by igor-m** [comment]
Ok, now we have 201points back, but your calculation has to be adjusted too, it seems.
1. it does wrongly recalculate the markers freqs (automatic one)
2. it shows 904 MHz in the graph where we sweep till 900M only..
See below
![201points](https://user-images.githubusercontent.com/7240123/89022072-ba3a8400-d321-11ea-8f46-0f25b2e7428f.PNG)

**Comment by zarath** [comment]
that was a small glitch in the multi segment step size rounding. its now closer to the stop. but it depends on span, points and segments if it is possible to be spot on.

**Comment by igor-m** [comment]
OK, but why you the mid and stop frequencies in Marker2 and Marker3 are divided by 2 when I set 201points?
And then you divide by 10 with Segments set to 10..
The Marker frequencies should stay same for 101 and for 201points and/or XX segments (plus minus).
![Marker2 and Mrker3 problem with 201points](https://user-images.githubusercontent.com/7240123/89033371-ef9d9c80-d336-11ea-8df0-c0a4ba984f52.PNG)
![Marker2 and Mrker3 problem with 201points and 10 segments](https://user-images.githubusercontent.com/7240123/89033379-f3c9ba00-d336-11ea-86d1-841a33d95f6c.PNG)

**Comment by zarath** [comment]
That is a different bug. It looks like i calculate marker settings on base of first segment...
