### ISSUE TITLE
Can't find the nanovna-saver.exe file

### ISSUE THREAD

**Issue by Saga24** [NanoVNA-Saver/nanovna-saver#302]
Hi.

Can you please help me, I can´t find the newest nanovna-saver-v0.2.2-1.exe file to run on Windows 10 32bit?

When I run "NanoVNASaver.windows-latest.zip" I get an error, thats it is not working on my Windows version?

The latest version I got is "nanovna-saver-v0.2.2-1.exe"

Any help please..

Saga24

**Comment by zarath** [comment]
There is no official 32Bit exe > 2.2.1 

see #284
