### ISSUE TITLE
Marker2 and Marker3 pre-calculated values should stay (aprox) the same for any number of points or segments

### ISSUE THREAD

**Issue by igor-m** [NanoVNA-Saver/nanovna-saver#303]
Currently the Marker2 and Marker3 pre-calculated values depends on the number of points and segments.
See below. They should stay roughly the same for any number of points and segments.
![Marker2 and Mrker3 problem with 201points](https://user-images.githubusercontent.com/7240123/89034371-1a88f000-d339-11ea-88ad-20971497c495.PNG)
![Marker2 and Mrker3 problem with 201points and 10 segments](https://user-images.githubusercontent.com/7240123/89034381-1fe63a80-d339-11ea-8616-223819576f28.PNG)

**Comment by zarath** [comment]
It's harder to fix as it seems on the first glance.
As currently data readout (and markers) depend on the measured data point an not on the selected frequency, markers keep their location in the dataset, so if marker is on 10th measured point it will keep that position even if the step width change
Will be fixable if this  current prinzipel will fundamentally changed to a frequency based view.
