### ISSUE TITLE
Setup when starting the nanovna-saver

### ISSUE THREAD

**Issue by PY3IG** [NanoVNA-Saver/nanovna-saver#314]
- When we only have two active graphics, it is necessary to scale the window size when starting the nano-saver. (Figures 1 and 2)

- Is it possible to hide the markers when starting? They are present in the graph immediately when connecting the nanovna to the nanovna-saver. (Figure 3). I want to use markers, but I would like to see when selected.

These two cases are not manifested in nanovna-Saver 0.3.6

Thank you for your work
73!
Igor Jobim
![saver_ini1](https://user-images.githubusercontent.com/56711292/89696259-703b3a80-d8ed-11ea-8201-0de7215428f5.PNG)
![saver_ini2](https://user-images.githubusercontent.com/56711292/89696261-70d3d100-d8ed-11ea-87d9-df49a96266c4.PNG)
![saver_ini3](https://user-images.githubusercontent.com/56711292/89696263-716c6780-d8ed-11ea-92fc-044bfd7de898.PNG)

**Comment by G4GCL** [comment]
These problems are also on the final version of V0.3.7. The window is the same size with up to 4 active graphics and expands slightly with 5 or 6 graphics. The provision of 5 markers is very good but it should be possible to use less than that.

Thank you for all your work on this fantastic software.
73,
John

**Comment by zarath** [comment]
@G4GCL don't know what about 5 markers? 
I initialize 3 if no .ini is present (eg. first installation)
Markers can be added or removed via the Display Setup window. - If there is a problem. That would be a new issue.

**Comment by zarath** [comment]
Thiis bug will be fixed in v0.3.8 (it's fixed by https://github.com/NanoVNA-Saver/nanovna-saver/commit/6f0f55ab798e19a86a7603f3197351dd1061a609)
