### ISSUE TITLE
Include estimated time in sweep control

### ISSUE THREAD

**Issue by ZeroChaos-** [NanoVNA-Saver/nanovna-saver#318]
Love the software, works great, thanks for that :-)

One missing feature is an estimated time till completion.  The percentage timer is nice, but with longer running sweeps it can take a while, and an estimate would be nice.

Additionally, it would be nice to have the estimate before the sweep is started, based on the settings of start/stop/step.  I imagine these are reasonably predictable in speed, so the estimate should be at least usefully accurate.

Thanks for the consideration.

**Comment by zarath** [comment]
It would be nice but it's impossible to estimate if retries during data gathering are needed.. An somewhat hard to implement too..

(You remember windows installer progress bars? ;-) )
