### ISSUE TITLE
NanoVNA-Saver 3.8 pre division by 0

### ISSUE THREAD

**Issue by PA3CCE** [NanoVNA-Saver/nanovna-saver#320]
This morning I started a fresh calibration in NanoVNA-Saver 0.3.8 pre, 1MHz to 2GHz, 10 Segm,ents, 401 datapoints, 100 Hz Bandwidth. The "short" caalibration went well, but while running the "open" calibration I got a "divide by "zero" errormessage.
See screenshot and errormessage "calibration.txt".

![Schermopname (61)](https://user-images.githubusercontent.com/14205041/90759479-c4c4b980-e2e0-11ea-8060-657083388d04.png)

[calibration.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/5102334/calibration.txt)

Jos

**Comment by MZachmann** [comment]
When the sweep fails it returns a zero length array of data that causes a crash. The stack is shown in the calibration.txt.

**Comment by zarath** [comment]
Zero length of array is checked in newer versions
