### ISSUE TITLE
ERROR DURING SWEEP argument out of range with NanoVNA V2

### ISSUE THREAD

**Issue by ok1vaw** [NanoVNA-Saver/nanovna-saver#327]
**Describe the bug**
when changing number of points  this error appears. if you confirm it, nanovna saver continues with those borders OK.
**To Reproduce**
1. set 51 points sweep from 1MHz to 60MHz, make a sweep.
2.change the 60MHz to 64MHz
3. push sweep again
4. Error appears.
5.click OK
6. Sweep starts.

**Expected behavior**
This should not happen.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win 10
 - Python version: [if applicable]
 - NanoVNA-Saver version: [e.g. 0.1.4] 0.3.7
![error during sweep](https://user-images.githubusercontent.com/6250023/93018182-26b9cb80-f5ce-11ea-9e3f-dc1ceb880b4e.jpg)
[debug for test2.txt](https://github.com/NanoVNA-Saver/nanovna-saver/files/5214086/debug.for.test2.txt)

**Additional context**

**Comment by Mike4U** [comment]
see #322 at Mike4U.  This finally worked for me on NanoVNASaver 0.3.8 pre03 but I think it will make other versions work too.
