### ISSUE TITLE
0.3.7 NanoVNA Saver Unable to parse version: 0-2-1 with NanoVNA-F 

### ISSUE THREAD

**Issue by cache4pat** [NanoVNA-Saver/nanovna-saver#329]
![NanoVNASaver_ErrorReport](https://user-images.githubusercontent.com/71838476/94168940-2d610200-fe5c-11ea-9554-1fed272469d2.jpg)

**Describe the bug**
0.3.7 NanoVNA Saver Unable to parse version: 0-2-1 with NanoVNA-F 

For the first time, I have hooked my new NanoVNA-F via my Windows 10 HP Envy (core i7) Com USB Port 4, to NanoVNASaver with version 0.3.7 installed.

The software connected, but then reported the ERROR shown in the attached image.

**Expected behavior**
Error free operation; data to appear on the graphic displays. Result .. Nothing  

**Screenshots**
See attached Image
![FirstConnectedImage](https://user-images.githubusercontent.com/71838476/94169801-3c947f80-fe5d-11ea-9189-433766cd8983.jpg)

![NanoVNASaver_ErrorReport](https://user-images.githubusercontent.com/71838476/94169858-503fe600-fe5d-11ea-942e-57b7e204fce5.jpg)

![Laptop](https://user-images.githubusercontent.com/71838476/94170190-c04e6c00-fe5d-11ea-812a-2b7498ca453a.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] :HP Laptop running Windows 10 'HOME Edition' Version 1903 - See Images Provided
 - Python version: Version 3.8
 - NanoVNA-Saver version: [e.g. 0.2.1]

**Additional context**

**Comment by tczerwonka** [comment]
I just encountered the same problem on Ubuntu 20.04, latest saver code from git.  I removed my NanoVNASaver.ini and the software continued and functioned as expected.  Not a fix, but maybe a workaround.

**Comment by astrocfi** [comment]
I just ran into the same problem with 0.3.8 and the NanoVNA-F. I removed the NanoVNASaver.ini file as suggested by @tczerwonka, but it didn't help. I'm running Windows 10.

If you need help debugging this I'm happy to help. I'm an experienced Python developer.

**Comment by DL1ABR** [comment]
astrocfi wrote and I have the same problem:
I just ran into the same problem with 0.3.8 and the NanoVNA-F. I removed the NanoVNASaver.ini file as suggested by @tczerwonka, but it didn't help. I'm running Windows 10.
Sometime Saver is running properly for some short time, then it quickly freezes - No Respond.
Restart Saver helps sometimes, sometimes not and Saver freezes at once after start. 
Restart of PC helps sometimes, sometimes not and Saver freezes at once after start.

**Comment by DL1ABR** [comment]
I experienced as follows and SAVER is running much more stable:
I took a USB 2.0 port - not a USB 3.0 port.
I use the 32 bit version - not the 64 bit version.
Once if I run the 64 bit version, PC needs restart so that the 32 bit version is running.
