### ISSUE TITLE
logarithmic scaling of graphs

### ISSUE THREAD

**Issue by UlrichD61** [NanoVNA-Saver/nanovna-saver#33]
Hello, me again.

After quite successfully using NanoVNA for impedance measurement of EMC components I'm asking if it's possible to add an option for the graphs to display in logarithmic scaling. Ideally selectable for amplitude and/or frequency.
That logarithmic scaling is the industry standard when looking into datasheets and having same scaling in nanovna-saver would be very helpful.

just  a thought.....

Here an example of a ferrite-core in logarithmic scaling.
![grafik](https://user-images.githubusercontent.com/56156578/66334203-d7d4d200-e938-11e9-8b1f-b99189bb8d2a.png)

**Comment by mihtjel** [comment]
I had log scaling of frequency on the list, but I had not yet considered log scaling of impedance as well. Interesting point. I will put it on the wishlist :-)

**Comment by UlrichD61** [comment]
Thanks, you are a star !!

Ulrich 




⁣TypeApp for Android herunterladen ​

**Comment by mihtjel** [comment]
Log scaling of the frequency axis is in for 0.1.3.

Log scaling of the data axis: Which charts would it be relevant for? I'm thinking only Q and R+jX make sense?

**Comment by UlrichD61** [comment]
Hello
Yes I think so too. 

Most other graphs are in dezibel, that is already logarithmic scaling. 

Cheers & Thanks for all effort into that!

Ulrich 



⁣TypeApp for Android herunterladen ​

**Comment by UlrichD61** [comment]
Hello mihtjel,
once more a lot of thanks for all effort on Saver 1.5.  I'm sure the whole community is extremely greatful.

Regarding the logarithmic scaling of frequency, is there any chance to devide the screen into "decades" rather than equidistance scaling with odd numbers ?
Having the classic way of showing decades e.g. lines at 1 MHz, 10 MHz, 100 MHz..... (or even fractions ) would make it more useful and compatible to the standard.

Just a thought :-)

**Comment by mihtjel** [comment]
Hello Ulrich,
it's certainly on the TODO list, but I still need to figure out a good way to do it :-)

**Comment by UlrichD61** [comment]
Hello, me again. 
Just two more enhencement ideas:  

It is great to have the S11 |Z| available in the chart-selection.
Would it be a problem to add S11 |Z| also into the **"Marker Settings"** to the have the actual impedance as number ?

Additionally a little "**Text-Window**" in the graph image would be ideal to allow commenting the image before saving.
 
Thanks !

PS:
...... the decade-devided logartithmic frequency scaling is still on my Christmas wish list :-).
See post from Nov. 8th.  Unfortunately I'm not a SW programmer to support any of the topics with some  coding.

**Comment by UlrichD61** [comment]
sorrry, closed by accident and reopenened again

**Comment by rjordans** [comment]
#377 should fix the logarithmic plotting party of this

**Comment by ikatkov** [comment]
Arguably, this is different from what the OP has been asking for.
The point of having industry standard graphs is to be able to make quick visual comparison.

These two charts show the same data, but the look completely different.

![image](https://user-images.githubusercontent.com/1211343/227017871-4f5567bd-e601-435c-ad3d-5b9ec6f13be7.png)

![output](https://user-images.githubusercontent.com/1211343/227018106-954a4ba2-07dc-4cce-a513-7a7ae2a4ab9f.png)

When one compares their own local measurements with manufacturer's 
![image](https://user-images.githubusercontent.com/1211343/227018396-d3a3c297-395c-4d1c-a475-5e1131e51275.png)

lack of proper log scale is very visible
