### ISSUE TITLE
support newer scipy

### ISSUE THREAD

**Issue by ZeroChaos-** [NanoVNA-Saver/nanovna-saver#332]
please consider adding support for scipy-1.5

**Comment by barjac** [comment]
Yes we can't maintain nanovna-saver for our next distro release if python-scipy can't be >= 1.5, we are at python3-scipy-1.5.2 now and are approaching release version freeze.
Increasing the version restriction to < 1.5.5 arbitrarily in setup.py does not break the build against 1.5.2, but whether it will affect runtime I have no idea yet.

**Comment by zarath** [comment]
done in v0.3.8
