### ISSUE TITLE
V0.3.7 x64  "Manage Bands, only input until 2100000000Hz. For QO100 2400000000Hz not possible"

### ISSUE THREAD

**Issue by DL9NAZ** [NanoVNA-Saver/nanovna-saver#340]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Python version: [if applicable]
 - NanoVNA-Saver version: [e.g. 0.1.4]

**Additional context**

**Comment by zarath** [comment]
done in v0.3.8

**Comment by DL9NAZ** [comment]
Danke für die Antwort,

habe es leider zu spät gesehen.

73 de Knut

Von meinem iPhone gesendet
