### ISSUE TITLE
Show Bands will not highlight when sweep limits match band limits

### ISSUE THREAD

**Issue by KK1L** [NanoVNA-Saver/nanovna-saver#344]
**Describe the bug**
NanoVNASaver version 0.3.7 communicating with NanoVNA-H v0.4.5-1-gfbbceca
When displaying a sweep with the start and stop limits matching the band limits the graph/chart will not be highlighed.

**To Reproduce**
1. Go to 'Display setup ..."
2. Click on 'Show bands'
3. Set Sweep control  'Start' and 'Stop' to be equal to a bands limits

**Error behavior**
![NanoVNAMissingBand](https://user-images.githubusercontent.com/73606166/97469965-5bcf7280-191d-11eb-906b-88bdc3021790.JPG)

**Expected behavior**
![NanoVNACorrectBand](https://user-images.githubusercontent.com/73606166/97469966-5bcf7280-191d-11eb-8de4-25794e358002.JPG)

**Comment by zarath** [comment]
Exact. That behaviour was intended as you don't gain much information if you are completely in a band or completely outside.

Perhaps one can implement another config option....
