### ISSUE TITLE
Xubuntu 20.04 issue

### ISSUE THREAD

**Issue by jackdev23** [NanoVNA-Saver/nanovna-saver#361]
After installing cannot run the program with this message: 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

SOLUTION 
Install PyQT5 , in my case I use :
synaptic and I installed python3-pyqt5

Hope this help,
73 IW2NDH

**Comment by cronyx** [comment]
sudo apt install qt5dxcb-plugin

**Comment by ntoulasd** [comment]
> sudo apt install qt5dxcb-plugin

This help me also in Ubuntu 20.04
