### ISSUE TITLE
Communication error during sweep 

### ISSUE THREAD

**Issue by df5hc** [NanoVNA-Saver/nanovna-saver#366]
**Describe the bug**
During calibration process the communication to the nanovna-f V2 sees disrupted sometimes. An error message occours and the seep is stopped during the sweep.

Error message:
Error during sweep
Stopped
Cannot configure port, somethimng went wrong. Original message OSError (22, 'Das Zeitlimit für die Semaphore wurde erreicht.' , None, 121 )        
OK

**To Reproduce**
1. NanoVna-F V2 ( from Sysjoint) connected via USB, connection established, data coming.
2. Set Frequency  ( example full span : 50k to 3GHz )
3. Click on calibration, start the OSLIT calibration.
3. First calibrations sweeps ok  ( example short and open )
4. During Load calibration the sweep stops suddenly. Happens also during Through calibration, seems random. And the error message occours. Klick OK.
5. Start sweep manually again, works sometimes.
6. sometimes the calibration confirmation comes 

**Expected behavior**
A undisrupted calibration process.

**Desktop (please complete the following information):**
- Windows 10
- NanoVna Saver V 0.3.8
- NanoVNA-F V2 Firmware 0.1.0  ( newest)

**Comment by ok1vaw** [comment]
See my similar posts- try to connect directly with best USB cable without using any USB HUB, try both USB3 or USB2 if available.
