### ISSUE TITLE
Use as a frequency generator.

### ISSUE THREAD

**Issue by ortegahernandes** [NanoVNA-Saver/nanovna-saver#393]
Currently the "nanovna saver" does not allow to put the stimulus (start and stop) via PC on the same frequency
EX:
start: 433Mhz
stop: 433Mhz.

However, in the device it is possible to make such a configuration and use it as a frequency generator, only a specific frequency instead of a scan.

**Comment by ok1vaw** [comment]
The CW generator function is only available from the Nanovna (V2) itself. The  V2+4 unfortunately has not the CW implemented.

**Comment by ortegahernandes** [comment]
> The CW generator function is only available from the Nanovna (V2) itself. The V2+4 unfortunately has not the CW implemented.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
English is not my native language, so I may not have understood it well.
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
My nano vna - H4 has this function (CW). just put the same frequency in start and stop.

How far do I know the H4 version is the (V1) correct?

is running the latest available firware.

[](https://github.com/hugen79/NanoVNA-H/releases/tag/1.0.45)

only that the nanosaver software does not allow to place the same frequency.

**Comment by zarath** [comment]
As it depends too much on type of device and firmware I see no value in implementing this.

**Comment by ok1vaw** [comment]
Using NanoVNA (V2) as a CW generator is a very usefull function and its enhancing its value for RF measurement. I vote for leaving it there, where it works.
