### ISSUE TITLE
After building it, NanoVNA-Saver 0.3.10rc2 not running

### ISSUE THREAD

**Issue by PA3CCE** [NanoVNA-Saver/nanovna-saver#411]
**Describe the bug**

After "Successfully installed NanoVNA-Saver-0.3.10rc02"  in the command-window and running nanovnasaver.exe I finally get :

NanoVNASaver.py , line27 , in <module> from .Windows Import ( ModuleNotFoundError: No module named 'NanoVNASaver.windows'

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Python version: 3.9
 - NanoVNA-Saver version: NA

**Additional context**
NanoVNASaver 03.10rc01 is running well after building.

**Comment by zarath** [comment]
0.3.10rc2???

**Comment by zarath** [comment]
Ok. I see setuptools makes an rc out of pre in its version evaluation ;-)

**Comment by PA3CCE** [comment]
Ok, downloaded the latest sources, but now I get a similar message "no module named  NaanobnaSaver.Hardware.TinySA.

Sorry,
Jos

**Comment by zarath** [comment]
Strange...

**Comment by PA3CCE** [comment]
This morning I downloaded the latest sources and **rc4** runs fine !!
Thank you,
Jos
