### ISSUE TITLE
NanoVNA-Saver 0.3.9 pre04 problems

### ISSUE THREAD

**Issue by PA3CCE** [NanoVNA-Saver/nanovna-saver#414]
**Describe the bug**

As said,  now I can start **pre04** OK, but while measuring an inductor I have 2 problems that I did not have previously. 

My settings :
I used the calibration file made in rc1
The device was a NanoVNa V2.2 and "Manage/Device" settings in NanoVNA-Saver was set to 1023 datapoints.
"Sweep settings" was set to "Average sweep 3/0".

problems:

1) After sweeping an inductor (13-15MHz) the Serial L chart shows no trace  (Serial C chart shows a trace with negative values as          it should).

2) When I set "Sweep settings" in NanoVNA-Saver to  more than 1,  NanoVNA-Saver aborts after sweeping the first segment.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.9
 - NanoVNA-Saver version: 0.3.9 pre04

Regards,
Jos

**Comment by PA3CCE** [comment]
PS
When I increase the stop frequency until it passes the selfresonant frequency of the inductor (starts showing negative values), the strace starts showing !!

**Comment by PA3CCE** [comment]
PS1
All works fine when I do a "normal" S21 measurement ; NanoVNA-Saver is not aborting @ >1 Sweep settings etc.
Data-axis setting OK now, except for  decimal settings , eg -19.5 entered is set as -195 in the chart.

**Comment by zarath** [comment]
Ok or not OK, this is here the question?

**Comment by PA3CCE** [comment]
This is what I meant :
Setting negative values for the data-axis is OK now, but there still is some problem with entering decimal values.
The aborting of the program when measuring an inductor with "Sweep settings">1  exists.
When having measured an inductor no trace in the Series-L chart , when there is no negative measurement in the scan  exists.

I hope all is clear now.

**Comment by PA3CCE** [comment]
Addition to my last message 

The program does not abort when "Sweep settings" is set > 1 WHEN AN S21! MEASUREMENT is performed .
its is aborting WHEN A Series-L MEASUREMENT is performed., and "Sweep settings" is set to >1
