### ISSUE TITLE
NanoVNA Saver com port error in Windows 10 21h1

### ISSUE THREAD

**Issue by Plohse1963** [NanoVNA-Saver/nanovna-saver#429]
The current NanoVNA Saver 0.3.9 Windows executable is exhibiting Com port access error when used on Windows 10 Pro 64 bit version 21h1 (19043.1202).
NanoVNA Saver loads but when connecting device "Connec to device" the CMD window report the following:
"ettings: C:/Users/plohs/AppData/Roaming/NanoVNASaver/NanoVNASaver.ini
2021-09-14 17:27:45,081 - NanoVNASaver.NanoVNASaver - ERROR - Tried to open COM3 (NanoVNA) and failed: could not open port 'COM3': PermissionError(13, 'Access is denied.', None, 5)"
Tried on several differeny PC's with same OS version.
NanoVNA-F V2 connects OK with other applications on same PC's.
Any suggested solution?

**Comment by CJC-HOB** [comment]
### **NanoVNA Saver 0.3.9 + Windows 10 20H2+ NanoVNA-F V2**
NanoVNA Saver 0.3.9 Windows 64 Bit Version executable unable to connect to COM Port on NanoVNA-F V2 (WWW.SYSJOINT.COM) Firmware v0.3.0 Hardware Rev.C  Build Time Aug 17 2021 - Perhaps similar problem to others reported.

Windows PC Details
Edition	Windows 10 Pro
Version	20H2
Installed on	‎07/‎03/‎2021
OS build	19042.1237
Experience	Windows Feature Experience Pack 120.2212.3530.0

With the same computer the internal drive of the NanoVNA can be accessed using the same USB cable provided with the unit and the firmware file has been transferrred and updated successfully.  This suggests the cable and computer connection are working.

A test using a serial com port terminal program has managed to open the COM port and commands can be sent to the NanoVNA and responses received.  However the COM port cannot be opened reliably each time and sometimes fails to open.

A different laptop computer running a similar version of Windows 10 has also been tried with no difference noted.

The NanoVNA Saver Windows Command Window closes when the program crashes before the error messages can be copied to a text file.  No log files for NanoVNA Saver have been found.

Just bought this new NanoVNA and a little dissapointed that the program doesn't work.  I am happy to do any testing that will help the authors of the software to resolve this issue.

Many thanks.
