### ISSUE TITLE
nanovna-save crashes when connecting to Aursinc nanovna SAA-2N

### ISSUE THREAD

**Issue by pburns001** [NanoVNA-Saver/nanovna-saver#434]
![nanosaver_error](https://user-images.githubusercontent.com/12852113/134430993-cfc957ad-1938-465a-b61f-45809525d0b5.PNG)

**Comment by pburns001** [comment]
If I already have it in usb mode by first connecting to VNA_QT and terminating vna_qt, it connect without error.

**Comment by JamesLPearson** [comment]
I have the same issue. 

> If I already have it in usb mode by first connecting to VNA_QT and terminating vna_qt, it connect without error.
Thank you for that workaround - that worked for me too. Opened VNA_QT, selected the COM port and connected. That put the NanoVNA into 'USB Mode', which allowed NanoVNA_Saver to work. 

Seems like NanoVNA _Saver is not making the device enter USB Mode for some reason.
