### ISSUE TITLE
an unhandled win32 exception occured in nano-saver.exe [4304]

### ISSUE THREAD

**Issue by iutech-france** [NanoVNA-Saver/nanovna-saver#435]
**Describe the bug**
On launching nanosaver.exe (both version 0.3.9 and 0.3.8) on Windows7 I get the message "an unhandled win32 exception occured in nano-saver.exe [4304]" and then I have only two options, "debug" (which doesn't seem to produce anything) and "close the program".

**To Reproduce**
Click on nanovna-saver.exe

**Expected behavior**
That nanoVNA saver launches without crashing just afterwards.

.
**Desktop (please complete the following information):**
 - Windows 7 Pro
 - Python version: how to check ? Not sure there is one installed
 - NanoVNA-Saver version: [both 0.3.9 and 0.3.8]

**Comment by iutech-france** [comment]
Trying on a Windows 10 VM the problem doesn't appear; but on physical machines the crash appeared systematically on the two Windows 10 computers I tried nanovna-saver on.

**Comment by iutech-france** [comment]
Also it offers to debug the crash for me, but the default debugger is Microsoft Visual Studio that refuses to work due to a license problem.
Which other debuggers could be used ?
Is there a way to find log files somewhere that could explain why it crashed ?

**Comment by zarath** [comment]
No resources for fixing build on outdated/obsolete windows versions.
Perhaps newest release will work?
