### ISSUE TITLE
version 0.3.10 pre06 calibration not working

### ISSUE THREAD

**Issue by PA3CCE** [NanoVNA-Saver/nanovna-saver#436]
I'm trying to perform a 2 port calibration between 1 and 1.1 GHz, when it finishes  the S21chart shows a straight line at abt -2 dB (these are the uncalibrated measured values I think) and when I press "Apply" I expect to see a straight line at 0dB, but i get a very noisy display at abt -10dB.

Jos

**Comment by silbe** [comment]
You may be running into #349.

**Comment by zarath** [comment]
Changed calibration method in newer releases
