### ISSUE TITLE
Automatic cal loading at startup

### ISSUE THREAD

**Issue by charlesh3** [NanoVNA-Saver/nanovna-saver#462]
Could Saver automatically load a config file at startup?

This would be the equivalent  of the NanoVNA's using the default config at power on.

Chuck

**Comment by UlrichD61** [comment]
Config File loading at startup would definitely be a wonderful feature! 
I'm using NanoVNA-&Saver extensively for impedance measurements on ferrites
My setup is always one out of two or three choices. 

So Ideally saver would save **all** settings, like it already does right now for the display & marker setup.
- Markers frequencies, 
- Sweep control settings (start/stop)
- Calibration file name. 
Even better would be an option to save/reload various individual configs. 

Thanks
Ulrich
