### ISSUE TITLE
hugen79/NanoVNA-H version 1.1 not recognized

### ISSUE THREAD

**Issue by dhalbert** [NanoVNA-Saver/nanovna-saver#483]
I recently bought a new NanoVNA-H, which was loaded with https://github.com/hugen79/NanoVNA-H/releases/tag/1.1.

`Version.py` did not like this `x.x` version number, and complained with "Unable to parse version: 1.1". The unrecognized version may have caused some problems fetching data from the NanoVNA-H: I was getting scan values that did not match what the unit was reporting on the screen.

I fixed the problem by updating to https://github.com/hugen79/NanoVNA-H/releases/tag/1.1.01.

I'm not sure whether NanoVNA-Saver should support non-`x.x.x` version numbers, or whether https://github.com/hugen79/NanoVNA-H should avoid non-`x.x.x` releases. Probably both is good. I'll file an issue there as well.

**Comment by zarath** [comment]
Even if its not a version that matches modern semantic version scheme, I've implemented a fix, that nanovna-saver can cope with it.
