### ISSUE TITLE
NanoVNA-Saver version 0.4.0 Marker 2 Error

### ISSUE THREAD

**Issue by PA3CCE** [NanoVNA-Saver/nanovna-saver#489]
I`m measuring the response of a filter (S21 Gain), using NanoVNA-Saver V0.4.0 and my LiteVNA..
The markers 1 and 3 are shown in the graph , but marker 2 is not visible, the data is shown correctly.

**Comment by gaionim** [comment]
Can you try to change color and/or increase dimension ?

**Comment by PA3CCE** [comment]
Hi Gaionim,
I remamber the demensions of markes 1 and 3 wre VERY tiny at that moment.
I don`t have the filter I measured before at hand at the moment, so I just measured the S21 of a short (uncalibrated) and this time all three markers show up  and are NOT THAT tiny as previously, so ???
I will  do some more testing and will let you know when I can reproduce the error.
Sorry

**Comment by gaionim** [comment]
I think the problem not is in the data, so i guess it is resolved ;-)

For me was the combination of small dimension of the marker AND the color;
changing color or increasing dimension solved the issue ( at least in my case ).

If no more problem, can you close the issue ?
You'll can reopen if/when returns.

**Comment by PA3CCE** [comment]
Yes I will close the issue, when it shows again I will reopen it..
To me it looks like it was related to the very tiny demensions , they were extreem small indeed originally, hardly visible..
Strange , I id not chance any setting !!
