### ISSUE TITLE
PyQt5 QPalette & QColor not supported on raspberry pi - Always return Black Color

### ISSUE THREAD

**Issue by cinosh07** [NanoVNA-Saver/nanovna-saver#49]
When the application is started with the import of  QPalette & QColor from PyQt5 library, all colors are returned black.

But by using QPalette & QColor from qtpy library it worked.

Maybe an import conditional to the host type could solved the problem?

Regards

**Comment by mihtjel** [comment]
This sounds very odd! I don't have a Raspberry Pi which has a display attached, but I think I can probably find one to debug it on. I'll have a look!

**Comment by cinosh07** [comment]
Hi Rune,

you don't need one.
There's a virtual image for vmware or virtualbox on the rpi website.

https://www.raspberrypi.org/downloads/

**Comment by mihtjel** [comment]
Interesting - I didn't know that was possible what with the different CPU type. Thanks, I'll give that a go. :-)

**Comment by cinosh07** [comment]
You're welcome !  ;-)

Just tell me if you want me to check on my side your solution.
