### ISSUE TITLE
A 'Reference' Marker

### ISSUE THREAD

**Issue by vreijs** [NanoVNA-Saver/nanovna-saver#493]
**Is your feature request related to a problem? Please describe.**
Being able to see the 'Reference' values at a Marker position

**Describe the solution you'd like**
Add a specific Marker for the Reference? Or that it runs with say Marker 1

**Describe alternatives you've considered**
An alternative could be that one is able to swap the 'sweep' with the 'reference'.

**Additional context**
Thansk for considering.

**Comment by gaionim** [comment]
Try https://github.com/NanoVNA-Saver/nanovna-saver/pull/496
