### ISSUE TITLE
NanoVNASaver 0.4.0 fails calibration

### ISSUE THREAD

**Issue by heribertmsb** [NanoVNA-Saver/nanovna-saver#523]
**Describe the bug**
Calibartion ends after apply with 
![Screenshot 2022-07-24 115023](https://user-images.githubusercontent.com/67979062/180643399-6b26274b-4a34-4012-bc61-11cfa149d83e.jpg)
![Screenshot 2022-07-24 115141](https://user-images.githubusercontent.com/67979062/180643402-f84f6264-c5de-4646-a78b-7754c2756778.jpg)

 NanoVNA-Saver version: 

![Screenshot 2022-07-24 123718](https://user-images.githubusercontent.com/67979062/180643425-e7ed89ad-a783-4ddc-b814-1d9694434cb8.jpg)

(64 bit version, running on WIN10)

I have tried several bands, some are working, some not.
Also entering small deviation in frequency for the bandwith makes no change

However calibration on the device works fine and the sweep can be loaded offline
I have checked the calibartion standards (Short/open/load) : they are ok

**Comment by kawalkQCWski** [comment]
can you try the latest firmware which is 1.04 ? 

https://deepelec.com/2022/04/02/deepvna_101_nanovna-f-1_0_4/

**Comment by heribertmsb** [comment]
I have diffrent Hardware: NanoVNA-F V2 Hardware rev. C (no thumbweel switch) by sysjoint. 
Also no "by BH5HNU mark on the PCB 
Here the link to my hardware:  https://sysjoint.com/en/content/?144.html
lateset firmware: http://www.sysjoint.com/file/NanoVNA-F_V2_App_v0.5.0.zip

**Comment by kawalkQCWski** [comment]
Thanks for that. I didn't realize that the V2 is a sysjoint product until yesterday,  Confusing naming.  Some people load the deepelec firmware into these but that creates other issues for the saver.  Not sure what if any hardware differences might be causing that as one seems to  be the clone of the other.  Maybe the processor used is not STM but alternative ?

**Comment by heribertmsb** [comment]
In the manual i found the following about the hardware
![grafik](https://user-images.githubusercontent.com/67979062/181000429-38d5d1c7-60c2-4dfe-8ee7-a81d2647666d.png)

**Comment by kawalkQCWski** [comment]
Definitely not complete - as it's missing the Ato D converter that makes
the F  perform quite well.

[image: image.png]

**Comment by kawalkQCWski** [comment]
VNA F 

![image](https://user-images.githubusercontent.com/49310052/181244175-c1473634-277f-4c88-82c6-c1765de0cb09.png)


VNA F-V2 

![image](https://user-images.githubusercontent.com/49310052/181244339-0763e41e-0e6d-487a-b156-7448f11616d4.png)

**Comment by kawalkQCWski** [comment]
GD32 is almost the same but a little faster and has different flash implementation

**Comment by kawalkQCWski** [comment]
Check this out  about the F-V2 and F 

https://github.com/NanoVNA-Saver/nanovna-saver/issues/523
