### ISSUE TITLE
 nanovna-saver saving plots from command line?

### ISSUE THREAD

**Issue by mik1234mc** [NanoVNA-Saver/nanovna-saver#529]
Hi all,

thank you for your nice application. I have a question if it is possible to dump nanovna data(touchstone format) using your application from command line; thus without pushing any buttons with a mouse.

Thank you,
Michael

**Comment by mik1234mc** [comment]
Just found: https://github.com/nanovna-v2/NanoVNA2-firmware/tree/master/python

**Comment by Ho-Ro** [comment]
@mik1234mc If you want more command line tools for NanoVNA: https://github.com/Ho-Ro/nanovna-tools
