### ISSUE TITLE
NanoVNA-Saver crashes during 'connect to device' on Mac Air M1 12.6 OS

### ISSUE THREAD

**Issue by good-point-lab** [NanoVNA-Saver/nanovna-saver#545]
**Describe the bug**
Latest NanoVNA-Saver crashes during 'connect to device' on Mac Air M1 12.6 OS

**To Reproduce**
1. Installed the latest 'Port'
2. Installed the Saver with 'sudo port install NanoVNASaver'
3. Rescanned serial port
4. Checked 'about', OK
5. 'Connect to device' results in to crash.  Always repeatable.

**Expected behavior**
The older version connected to the device and the 'sweep' worked.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX 12.6
 - Python version: installed along with 'sudo port install NanoVNASaver'
 - NanoVNA-Saver version: 0.4.0

**Additional context**
Please address this, feels like a show-stoper.

**Comment by zarath** [comment]
seems to be fixed
