### ISSUE TITLE
bug: Wont run on fedora 37

### ISSUE THREAD

**Issue by cacheflood** [NanoVNA-Saver/nanovna-saver#575]
Command line log:

NanoVNASaver 0.5.3

Copyright (C) 2019, 2020 Rune B. Broberg
Copyright (C) 2020ff NanoVNA-Saver Authors

This program comes with ABSOLUTELY NO WARRANTY
This program is licensed under the GNU General Public License version 3

See https://github.com/NanoVNA-Saver/nanovna-saver for further details.

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

(nanovna-saver:7384): GLib-GIO-ERROR **: 21:54:30.952: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Trace/breakpoint trap (core dumped)

**Comment by easytarget** [comment]
See #568 and #572,
This is fixed in `main`, but needs releasing

The official fedora package is broken by this, you will need to wait for the maintainer of that to patch it.

**Comment by LieBtrau** [comment]
FYI: This problem occurs also on Ubuntu 22.04.1 LTS, 64-bit, Wayland windowing system, Gnome version 42.5.

**Comment by zarath** [comment]
Fixed in #572 / v0.5.4
