### ISSUE TITLE
Windows 11 continuous sweep does not stop with STOP button. 

### ISSUE THREAD

**Issue by bearbate** [NanoVNA-Saver/nanovna-saver#589]
# Bug Report

**NanoVNA-Saver version:** 0.5.4

**Current behavior:**

Start continuous sweep  - click STOP button but sweep does not stop
**Expected behavior:**

Sweep should stop

**Steps to reproduce:**
As above description

Beyond my pay grade

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by rjordans** [comment]
I can confirm this also happens on Linux

**Comment by zarath** [comment]
See #128 
Any FW on any Device available which support disabling stimulus via command now?

**Comment by rjordans** [comment]
@zarath this seems to be a different issue. looks like [this line](https://github.com/NanoVNA-Saver/nanovna-saver/blob/f996ee9ceb22cbf8e717e10ff4083dd03e93bfb9/NanoVNASaver/SweepWorker.py#L137) misses an "or self.stopped"

**Comment by KJ7NLL** [comment]
+1, same issue, but we are in Linux running v0.5.4.  

if I open the "Sweep Settings" dialog and click it from "continuous" to "single" then it stops sweeping.  Then I put it back to "continuous" and click "sweep" to go back to continuous.  Ok for a work-around, but would be nice to click "Stop".

**Comment by rjordans** [comment]
This should be fixed as of version 0.5.5 and can probably be closed now.  @bearbate and @KJ7NLL can you confirm this now works as expected?
