### ISSUE TITLE
bug:  sweep color does not change without close/re-open

### ISSUE THREAD

**Issue by KJ7NLL** [NanoVNA-Saver/nanovna-saver#596]
# Bug Report

**NanoVNA-Saver version:**
0.5.4 on Linux

**Current behavior:**
Sweep color doesn't change "Display Setup" until I close and re-open 'saver.

**Expected behavior:**

Apply immediately, or have an "Apply" button.

**Steps to reproduce:**

1. Do a sweep
2. Open Display Settings
3. Change the Sweep Color
4. Color does not change.  I tried clicking "sweep" again to redraw, but doesn't help
5. But...closing and re-opening 'saver seems to work.

**Comment by barjac** [comment]
Can't that bot be turned off?
