### ISSUE TITLE
Displaying info about marker on graph

### ISSUE THREAD

**Issue by pedjas** [NanoVNA-Saver/nanovna-saver#65]
It would be good to have an option to turn on displaying some info about marker on graph itself) like frequency, impedance, VSWR..)

That would make graph more informative but also it would be then possible to save graph image displaying such information. Such image if shared or saved in project documentation would be more informative than just plain graph.

**Comment by DE8MSH** [comment]
Yes. I'm missing it too since yesterday -- I used NVNAS 1st time.

It's great btw.!
