### ISSUE TITLE
Add a feature

### ISSUE THREAD

**Issue by mend0z0** [NanoVNA-Saver/nanovna-saver#656]
**Additional context**
I would like to ask for an additional option to the app! That would be another COM port e.g. Arduino and sending a command to both NanoVNA hardware and the second hardware at exact same time. It'll help the user to sync the sweeping function with another activity!

I tried to use the source code but, all project files are missing! It'll be a great pleasure for me to contribute, otherwise, if you add this little extra option! It'll be great!

Looking forward to your reply!

Thanks!

**Comment by zarath** [comment]
I doubt, that exact sync is possible, as some devices do continous sweeps etc.
Easiest way to achieve a trigger would be a print statement in the SweepWorker.py.
Then you can catch it on the cmd line and pipe it to whatever command you want.
