### ISSUE TITLE
Arm64 build with memory limits.

### ISSUE THREAD

**Issue by jackokring** [NanoVNA-Saver/nanovna-saver#675]
**Is your feature request related to a problem? Please describe.**

Yes, it sure is at a freeze when doing an arm64 build and somehow over 2.0GB is used and er, locked up.

**Describe the solution you'd like**

I'd like a single core efficient on memory build option.

**Describe alternatives you've considered**

I've aliased make ... blah, blah.

**Additional context**

I'm not interested in an x86 build.

**Comment by zarath** [comment]
I guess target OS should be OpenBSD, right?

**Comment by jackokring** [comment]
Chromebook, debian container.

**Comment by dothebart** [comment]
most probably the required devices will not be visible within the container anyways.
