### ISSUE TITLE
bug: Measuring inductor core permeability --> popup menu crash !?...

### ISSUE THREAD

**Issue by Philmlg** [NanoVNA-Saver/nanovna-saver#677]
# Bug Report

**NanoVNA-Saver version: 0.6.2**

 Measuring inductor core permeability --> popup menu crash !?...

I am a new NanoVNASaver user, not very familiar with Python code !... A right clic on the S11 "mu" should open a popup menu ?.. But in my case (window10 64), => program crash !? have I missed a step ?

Your sincerly Phil (F6FSB)

**Comment by zarath** [comment]
fixed in 0.6.3... (pyinstaller is still strugling to create a working windows binary ...)
