### ISSUE TITLE
bug: nanoVNA-saver for Win64 crashes under wine64

### ISSUE THREAD

**Issue by alexlist** [NanoVNA-Saver/nanovna-saver#681]
# Bug Report

**NanoVNA-Saver version:**

v0.6.2

**Current behavior:**

Crashes under wine64

**Expected behavior:**

Does not crash.

**Steps to reproduce:**

Install wine64 under Ubuntu, download and unpack NanoVNASaver.win.x64.zip, run ```ẁine64 nanovna-saver.exe``` 

**Related code:**

n/a

**Other information:**

none

**Comment by zarath** [comment]
Use linux native version or source installation
