### ISSUE TITLE
feat: 0.6.3 - why no binary?

### ISSUE THREAD

**Issue by myhillman** [NanoVNA-Saver/nanovna-saver#686]
# Feature Request

**Describe the Feature Request**

Not all users, in fact the vast majority I suspect, are not able to build an executable. A binary should be a feature of every release

**Describe Preferred Solution**

Provide a binary

**Comment by ajawamnet** [comment]
yea really... too man-bun java jockey for me.  Include a binary.  I have work to do... not futzing around with your source tree.

**Comment by zarath** [comment]
> yea really... too man-bun java jockey for me. Include a binary. I have work to do... not futzing around with your source tree.
Then write your own Software and don't expect other people to write it for you in theirs leisure time!

**Comment by ajawamnet** [comment]
If it wasn't for us hardware guys you wouldn't have anything to write software on...
