### ISSUE TITLE
bug:  vertical data axis setting incorrect

### ISSUE THREAD

**Issue by ok1vaw** [NanoVNA-Saver/nanovna-saver#693]
# Bug Report

**NanoVNA-Saver version:**

0.55

**Current behavior:**

in case of changing the s11 to manual fixed setting 0dB maximum and -30dB minimum, the data could not be set

**Expected behavior:**
vertical axis should be set correctly

**Steps to reproduce:**

when entering maximum value (for example 0dB), after enter the whole range shifts correctly.
When entering minimum negative (such as -30dB), the range resets so some other range.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by zarath** [comment]
Please reopen iif still an issue with 0.6.4
