### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by PhilGoody** [NanoVNA-Saver/nanovna-saver#698]
# Bug Report

**NanoVNA-Saver version:**
0.5.5

**Current behavior:**
On MacOS 14.4.1 MacBook M3 installed with MacPorts
When the Enable Delta Marker checkbox is clicked the whole saver window begins to shake a shimmy.

**Expected behavior:**
The Delta marker should work, it doesn't.

**Steps to reproduce:**
Click the Enable Delta Marker checkbox.

**Related code:**

```
insert short code snippets here
```

**Other information:**
nanoVNA SAA-2N

**Comment by zarath** [comment]
Outdated version with previous Qt major versions
