### ISSUE TITLE
dev: Fix logarithmic sweep calculation

### ISSUE THREAD

**Issue by Peter3579** [NanoVNA-Saver/nanovna-saver#701]
In case that `logarithmic sweep` is enabled in the sweep settings, the (internally linearly sampled) segments of 101 data points do not have a proper logarithmic spacing. When multiple segments are used, the quotient of end_frequency by start_frequency for all segments should be the same. The attached diff fixes the issue and also a small error in the get_frequency() iterator. 

[logarithmic_sweep_diff.txt](https://github.com/user-attachments/files/15526168/logarithmic_sweep_diff.txt)

**Comment by zarath** [comment]
Can you fork main and create a PR with your patch?

That would be great!

**Comment by zarath** [comment]
Merged to main

**Comment by Peter3579** [comment]
Many thanks!
