### ISSUE TITLE
macOS build for latest

### ISSUE THREAD

**Issue by fred-corp** [NanoVNA-Saver/nanovna-saver#718]
Will there be a macOS build for the latest release ?

If not, are there instructions to compile from source ?

Thanks !

**Comment by aviatorhh** [comment]
There is a [build-macos-app.sh](https://github.com/NanoVNA-Saver/nanovna-saver/blob/main/build-macos-app.sh) in the root dir.

**Comment by rrobinett** [comment]
ON my Mac Mw running Sequoia 15.0.1:

./build-macos-app.sh         runs with warnings

but it doesn't run:

Robs-MacBook-Air-M2:nanovna-saver rob$ ./nanovna-saver.py
Traceback (most recent call last):
  File "/Users/rob/ham/nanovna-saver/./nanovna-saver.py", line 32, in <module>
    import NanoVNASaver.__main__
  File "/Users/rob/ham/nanovna-saver/./src/NanoVNASaver/__main__.py", line 31, in <module>
    from PyQt6 import QtWidgets
ModuleNotFoundError: No module named 'PyQt6'
Robs-MacBook-Air-M2:nanovna-saver rob$

**Comment by fred-corp** [comment]
I couldn't run the build script without errors either, but I managed to install the app with MacPorts ([instructions here](https://github.com/NanoVNA-Saver/nanovna-saver/blob/main/docs/INSTALLATION.md))

**Comment by rrobinett** [comment]
Thanks!  The MacPorts solved my problem
