### ISSUE TITLE
bug:  VT 3/70 security vendors flagged this file as malicious

### ISSUE THREAD

**Issue by eabase** [NanoVNA-Saver/nanovna-saver#721]
Virus Total flags this with 3 / 70 anti-virus vendors as malware. Not good, even if I am not concerned. 
Maybe try to address the issues causing this?

![2024-1118_232511_VirusTotal_-_File_-_5d2cb1b16f4367a05d58e847afbf8d](https://github.com/user-attachments/assets/2da3b28c-1774-4a62-b95f-6830fec3818b)

* https://www.virustotal.com/gui/file/5d2cb1b16f4367a05d58e847afbf8d9e8a1df5fea1d44475664690327705ab01?nocache=1

**Comment by zarath** [comment]
Older Version of f*ck*ng .exe?

This is a screenshot of the current v0.6.5 release binary
![Screenshot_20241119_212954](https://github.com/user-attachments/assets/37ab5973-f861-498f-9c9c-8bbcc5b66abe)

Snakeoil-Vendors ...
