### ISSUE TITLE
bug:  crash on intel mac while trying to connect to device

### ISSUE THREAD

**Issue by naiiawah** [NanoVNA-Saver/nanovna-saver#733]
# Bug Report

**NanoVNA-Saver version:**

v0.6.5 + a few commits (SHA b375d8e) on Mac Ventura v13.7.1 Intel

**Current behavior:** 

App crashes after pressing the connect to device button.

**Expected behavior:** 

Connects to device without crashing.

**Steps to reproduce:**

Build SHA b375d8e and execute the app.  Press the connect to device button, immediately crashes. Build the previous SHA and no crash.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by naiiawah** [comment]
I can supply the MacOS Problem Report (crash report) if needed.

**Comment by zarath** [comment]
Console output of during the crash would be nice. Preferably with -D debug.txt as startup option. Files can be uploaded to issues...

**Comment by naiiawah** [comment]
Here is the console output:

> brianm@Cosmos:~/Sources/Ham/nanovna-saver/dist/NanoVNASaver.app/Contents/MacOS ((HEAD detached at b375d8e))
> $ ./NanoVNASaver -D debug.txt
> NanoVNASaver 0.6.5.post1.dev8+gb375d8e
> 
> Copyright (C) 2019, 2020 Rune B. Broberg
> Copyright (C) 2020ff NanoVNA-Saver Authors
> 
> This program comes with ABSOLUTELY NO WARRANTY
> This program is licensed under the GNU General Public License version 3
> 
> See https://github.com/NanoVNA-Saver/nanovna-saver for further details.
> 
> Traceback (most recent call last):
>   File "NanoVNASaver/NanoVNASaver.py", line 569, in dataUpdated
>   File "NanoVNASaver/Windows/TDR.py", line 196, in updateTDR
> UnboundLocalError: cannot access local variable 'td' where it is not associated with a value
> Abort trap: 6
> brianm@Cosmos:~/Sources/Ham/nanovna-saver/dist/NanoVNASaver.app/Contents/MacOS ((HEAD detached at b375d8e))
> $ ls
> NanoVNASaver debug.txt

I've attached the "debug.txt" file.

[debug.txt](https://github.com/user-attachments/files/18030555/debug.txt)

**Comment by EnPassant123** [comment]
I think I found it.

Someone moved the logic for lowpass TDR to this function:
def _tdr_lowpass(self, tdr_format, s11, windowed_s11)

and the td variable is no longer in the same scope as the updateTDR function, which is causing the error.

**Comment by naiiawah** [comment]
That was my conclusion as well after I looked at the diffs of the TDR file between the SHA's.  Just wasn't sure of the right way to fix it.

**Comment by naiiawah** [comment]
Looks like the fix in merge #734 got eclipsed away by merge #735.

**Comment by zarath** [comment]
It was my fault, as I wanted to make the linter happy ... so I split out that function, not a aware of the scope of td data.

**Comment by naiiawah** [comment]
Just to be clear, this bug needs to be re-opened.  It is broken on HEAD again.
